---
version: 2

updates:
  - package-ecosystem: gomod
    directory: /telemetry-go
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /telemetry-core/deploy/production/local-webhook
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: cargo
    directory: /telemetry-rs
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      rust-dependencies:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /telemetry-py
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /telemetry-core/deploy/production
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
