// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: grafana/v1/dashboard_service.proto

// gRPC service for read-only access to Grafana-backed telemetry dashboards.

package grafanapbv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_grafana_v1_dashboard_service_proto protoreflect.FileDescriptor

const file_grafana_v1_dashboard_service_proto_rawDesc = "" +
	"\n" +
	"\"grafana/v1/dashboard_service.proto\x12\n" +
	"grafana.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1agrafana/v1/dashboard.proto2\x9c\x05\n" +
	"\x10DashboardService\x12\xb3\x01\n" +
	"\x15ListServiceDashboards\x12(.grafana.v1.ListServiceDashboardsRequest\x1a).grafana.v1.ListServiceDashboardsResponse\"E\xdaA\x06parent\x82\xd3\xe4\x93\x026\x124/v1/{parent=telemetryWorkspaces/*}/serviceDashboards\x12\xa0\x01\n" +
	"\x13GetServiceDashboard\x12&.grafana.v1.GetServiceDashboardRequest\x1a\x1c.grafana.v1.ServiceDashboard\"C\xdaA\x04name\x82\xd3\xe4\x93\x026\x124/v1/{name=telemetryWorkspaces/*/serviceDashboards/*}\x12\x87\x02\n" +
	"\x14LoadServiceDashboard\x12'.grafana.v1.LoadServiceDashboardRequest\x1a(.grafana.v1.LoadServiceDashboardResponse\"\x9b\x01\xdaATname,time_range_start,time_range_end,time_zone,variable_overrides,include_panel_data\x82\xd3\xe4\x93\x02>:\x01*\"9/v1/{name=telemetryWorkspaces/*/serviceDashboards/*}:load\x1a%\xcaA\"telemetry.the-protobuf-project.appB\x8d\x01\n" +
	"\x0ecom.grafana.v1B\x15DashboardServiceProtoP\x01Zbgithub.com/the-protobuf-project/telemetry/telemetry-go/protobuf/grafana/v1/grafanapbv1;grafanapbv1b\x06proto3"

var file_grafana_v1_dashboard_service_proto_goTypes = []any{
	(*ListServiceDashboardsRequest)(nil),  // 0: grafana.v1.ListServiceDashboardsRequest
	(*GetServiceDashboardRequest)(nil),    // 1: grafana.v1.GetServiceDashboardRequest
	(*LoadServiceDashboardRequest)(nil),   // 2: grafana.v1.LoadServiceDashboardRequest
	(*ListServiceDashboardsResponse)(nil), // 3: grafana.v1.ListServiceDashboardsResponse
	(*ServiceDashboard)(nil),              // 4: grafana.v1.ServiceDashboard
	(*LoadServiceDashboardResponse)(nil),  // 5: grafana.v1.LoadServiceDashboardResponse
}
var file_grafana_v1_dashboard_service_proto_depIdxs = []int32{
	0, // 0: grafana.v1.DashboardService.ListServiceDashboards:input_type -> grafana.v1.ListServiceDashboardsRequest
	1, // 1: grafana.v1.DashboardService.GetServiceDashboard:input_type -> grafana.v1.GetServiceDashboardRequest
	2, // 2: grafana.v1.DashboardService.LoadServiceDashboard:input_type -> grafana.v1.LoadServiceDashboardRequest
	3, // 3: grafana.v1.DashboardService.ListServiceDashboards:output_type -> grafana.v1.ListServiceDashboardsResponse
	4, // 4: grafana.v1.DashboardService.GetServiceDashboard:output_type -> grafana.v1.ServiceDashboard
	5, // 5: grafana.v1.DashboardService.LoadServiceDashboard:output_type -> grafana.v1.LoadServiceDashboardResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grafana_v1_dashboard_service_proto_init() }
func file_grafana_v1_dashboard_service_proto_init() {
	if File_grafana_v1_dashboard_service_proto != nil {
		return
	}
	file_grafana_v1_dashboard_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grafana_v1_dashboard_service_proto_rawDesc), len(file_grafana_v1_dashboard_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grafana_v1_dashboard_service_proto_goTypes,
		DependencyIndexes: file_grafana_v1_dashboard_service_proto_depIdxs,
	}.Build()
	File_grafana_v1_dashboard_service_proto = out.File
	file_grafana_v1_dashboard_service_proto_goTypes = nil
	file_grafana_v1_dashboard_service_proto_depIdxs = nil
}
