// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: grafana/v1/dashboard.proto

// Telemetry API messages for listing, reading, and loading Grafana-backed service dashboards.
//
// ServiceDashboard is the primary resource. GetServiceDashboard and LoadServiceDashboard
// return the full grafana_dashboard_document which maps 1:1 with dashboard.json.

package grafanapbv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Read-only Grafana-backed dashboard resource under a telemetry workspace.
//
// GetServiceDashboard returns grafana_dashboard_document populated with the full
// GrafanaDashboardAccessMeta tree (same shape as dashboard.json).
// ListServiceDashboards returns stubs without grafana_dashboard_document.
type ServiceDashboard struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource name. Format: `telemetryWorkspaces/{workspace}/serviceDashboards/{id}`.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Denormalized title from grafana_dashboard_document.spec.title; available in list results.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Full Grafana DashboardWithAccessInfo document. Populated on Get and Load; omitted on List.
	// Protojson of this message mirrors dashboard.json when marshalled with EmitUnpopulated=true.
	GrafanaDashboardDocument *GrafanaDashboardAccessMeta `protobuf:"bytes,3,opt,name=grafana_dashboard_document,json=grafanaDashboardDocument,proto3" json:"grafana_dashboard_document,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ServiceDashboard) Reset() {
	*x = ServiceDashboard{}
	mi := &file_grafana_v1_dashboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDashboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDashboard) ProtoMessage() {}

func (x *ServiceDashboard) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_v1_dashboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDashboard.ProtoReflect.Descriptor instead.
func (*ServiceDashboard) Descriptor() ([]byte, []int) {
	return file_grafana_v1_dashboard_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceDashboard) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceDashboard) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ServiceDashboard) GetGrafanaDashboardDocument() *GrafanaDashboardAccessMeta {
	if x != nil {
		return x.GrafanaDashboardDocument
	}
	return nil
}

// Request for ListServiceDashboards (AIP-132).
type ListServiceDashboardsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parent workspace. Format: `telemetryWorkspaces/{workspace}`.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Maximum page size; server may cap.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Opaque page token from a prior response.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// AIP-160 filter expression (title or tag predicates).
	Filter        string `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServiceDashboardsRequest) Reset() {
	*x = ListServiceDashboardsRequest{}
	mi := &file_grafana_v1_dashboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServiceDashboardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServiceDashboardsRequest) ProtoMessage() {}

func (x *ListServiceDashboardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_v1_dashboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServiceDashboardsRequest.ProtoReflect.Descriptor instead.
func (*ListServiceDashboardsRequest) Descriptor() ([]byte, []int) {
	return file_grafana_v1_dashboard_proto_rawDescGZIP(), []int{1}
}

func (x *ListServiceDashboardsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListServiceDashboardsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListServiceDashboardsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListServiceDashboardsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

// Response for ListServiceDashboards.
type ListServiceDashboardsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page of ServiceDashboard stubs (grafana_dashboard_document is always empty here).
	ServiceDashboards []*ServiceDashboard `protobuf:"bytes,1,rep,name=service_dashboards,json=serviceDashboards,proto3" json:"service_dashboards,omitempty"`
	// Token for the next page; unset when there is no further page.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServiceDashboardsResponse) Reset() {
	*x = ListServiceDashboardsResponse{}
	mi := &file_grafana_v1_dashboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServiceDashboardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServiceDashboardsResponse) ProtoMessage() {}

func (x *ListServiceDashboardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_v1_dashboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServiceDashboardsResponse.ProtoReflect.Descriptor instead.
func (*ListServiceDashboardsResponse) Descriptor() ([]byte, []int) {
	return file_grafana_v1_dashboard_proto_rawDescGZIP(), []int{2}
}

func (x *ListServiceDashboardsResponse) GetServiceDashboards() []*ServiceDashboard {
	if x != nil {
		return x.ServiceDashboards
	}
	return nil
}

func (x *ListServiceDashboardsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Request for GetServiceDashboard (AIP-131).
type GetServiceDashboardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full resource name of the dashboard to return.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceDashboardRequest) Reset() {
	*x = GetServiceDashboardRequest{}
	mi := &file_grafana_v1_dashboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceDashboardRequest) ProtoMessage() {}

func (x *GetServiceDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_v1_dashboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceDashboardRequest.ProtoReflect.Descriptor instead.
func (*GetServiceDashboardRequest) Descriptor() ([]byte, []int) {
	return file_grafana_v1_dashboard_proto_rawDescGZIP(), []int{3}
}

func (x *GetServiceDashboardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request for LoadServiceDashboard: optional time range, timezone, variable overrides.
type LoadServiceDashboardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full resource name of the dashboard to load.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Override range start (Grafana relative or RFC 3339). HTTP JSON key: "from".
	TimeRangeStart string `protobuf:"bytes,2,opt,name=time_range_start,json=from,proto3" json:"time_range_start,omitempty"`
	// Override range end. HTTP JSON key: "to".
	TimeRangeEnd string `protobuf:"bytes,3,opt,name=time_range_end,json=to,proto3" json:"time_range_end,omitempty"`
	// Override timezone (IANA id or "browser"). HTTP JSON key: "timezone".
	TimeZone string `protobuf:"bytes,4,opt,name=time_zone,json=timezone,proto3" json:"time_zone,omitempty"`
	// Per-load variable substitutions.
	VariableOverrides []*LoadServiceDashboardRequest_VariableOverride `protobuf:"bytes,5,rep,name=variable_overrides,json=variableOverrides,proto3" json:"variable_overrides,omitempty"`
	// When true, the server may evaluate panel queries and fill panel_data_json.
	IncludePanelData bool `protobuf:"varint,6,opt,name=include_panel_data,json=includePanelData,proto3" json:"include_panel_data,omitempty"`
	// Optional: Grafana instance base URL to fetch the dashboard live from Grafana's v2 API.
	// e.g. "http://localhost:3000"
	// When set, the server fetches the dashboard directly from Grafana using the dashboard
	// uid found in the stored grafana_dashboard_document.metadata.uid and returns the live
	// response instead of the cached version. The result is also updated in the store.
	// JSON key: "grafanaUrl"
	GrafanaUrl string `protobuf:"bytes,7,opt,name=grafana_url,json=grafanaUrl,proto3" json:"grafana_url,omitempty"`
	// Optional: Bearer token or Basic auth credentials for the Grafana API.
	// Format: "Bearer <token>" or "Basic <(user:pass)>"
	// If omitted, the request is made without Authorization header (works for Grafana with no auth).
	// JSON key: "grafanaToken"
	GrafanaToken  string `protobuf:"bytes,8,opt,name=grafana_token,json=grafanaToken,proto3" json:"grafana_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadServiceDashboardRequest) Reset() {
	*x = LoadServiceDashboardRequest{}
	mi := &file_grafana_v1_dashboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadServiceDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadServiceDashboardRequest) ProtoMessage() {}

func (x *LoadServiceDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_v1_dashboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadServiceDashboardRequest.ProtoReflect.Descriptor instead.
func (*LoadServiceDashboardRequest) Descriptor() ([]byte, []int) {
	return file_grafana_v1_dashboard_proto_rawDescGZIP(), []int{4}
}

func (x *LoadServiceDashboardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoadServiceDashboardRequest) GetTimeRangeStart() string {
	if x != nil {
		return x.TimeRangeStart
	}
	return ""
}

func (x *LoadServiceDashboardRequest) GetTimeRangeEnd() string {
	if x != nil {
		return x.TimeRangeEnd
	}
	return ""
}

func (x *LoadServiceDashboardRequest) GetTimeZone() string {
	if x != nil {
		return x.TimeZone
	}
	return ""
}

func (x *LoadServiceDashboardRequest) GetVariableOverrides() []*LoadServiceDashboardRequest_VariableOverride {
	if x != nil {
		return x.VariableOverrides
	}
	return nil
}

func (x *LoadServiceDashboardRequest) GetIncludePanelData() bool {
	if x != nil {
		return x.IncludePanelData
	}
	return false
}

func (x *LoadServiceDashboardRequest) GetGrafanaUrl() string {
	if x != nil {
		return x.GrafanaUrl
	}
	return ""
}

func (x *LoadServiceDashboardRequest) GetGrafanaToken() string {
	if x != nil {
		return x.GrafanaToken
	}
	return ""
}

// Response for LoadServiceDashboard.
type LoadServiceDashboardResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full ServiceDashboard including grafana_dashboard_document.
	ServiceDashboard *ServiceDashboard `protobuf:"bytes,1,opt,name=service_dashboard,json=serviceDashboard,proto3" json:"service_dashboard,omitempty"`
	// Resolved range start after applying request overrides (RFC 3339).
	EffectiveTimeRangeStart string `protobuf:"bytes,2,opt,name=effective_time_range_start,json=effectiveTimeRangeStart,proto3" json:"effective_time_range_start,omitempty"`
	// Resolved range end (RFC 3339).
	EffectiveTimeRangeEnd string `protobuf:"bytes,3,opt,name=effective_time_range_end,json=effectiveTimeRangeEnd,proto3" json:"effective_time_range_end,omitempty"`
	// Panel ref id → JSON-encoded data frames; populated only when include_panel_data was true.
	PanelDataJson map[string]string `protobuf:"bytes,4,rep,name=panel_data_json,json=panelDataJson,proto3" json:"panel_data_json,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadServiceDashboardResponse) Reset() {
	*x = LoadServiceDashboardResponse{}
	mi := &file_grafana_v1_dashboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadServiceDashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadServiceDashboardResponse) ProtoMessage() {}

func (x *LoadServiceDashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_v1_dashboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadServiceDashboardResponse.ProtoReflect.Descriptor instead.
func (*LoadServiceDashboardResponse) Descriptor() ([]byte, []int) {
	return file_grafana_v1_dashboard_proto_rawDescGZIP(), []int{5}
}

func (x *LoadServiceDashboardResponse) GetServiceDashboard() *ServiceDashboard {
	if x != nil {
		return x.ServiceDashboard
	}
	return nil
}

func (x *LoadServiceDashboardResponse) GetEffectiveTimeRangeStart() string {
	if x != nil {
		return x.EffectiveTimeRangeStart
	}
	return ""
}

func (x *LoadServiceDashboardResponse) GetEffectiveTimeRangeEnd() string {
	if x != nil {
		return x.EffectiveTimeRangeEnd
	}
	return ""
}

func (x *LoadServiceDashboardResponse) GetPanelDataJson() map[string]string {
	if x != nil {
		return x.PanelDataJson
	}
	return nil
}

// One variable substitution for this load.
type LoadServiceDashboardRequest_VariableOverride struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Template variable name without $ (e.g. "Robot", "Region"). JSON: "name".
	TemplateKey string `protobuf:"bytes,1,opt,name=template_key,json=name,proto3" json:"template_key,omitempty"`
	// Substitution value. JSON: "value".
	Substitution  string `protobuf:"bytes,2,opt,name=substitution,json=value,proto3" json:"substitution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadServiceDashboardRequest_VariableOverride) Reset() {
	*x = LoadServiceDashboardRequest_VariableOverride{}
	mi := &file_grafana_v1_dashboard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadServiceDashboardRequest_VariableOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadServiceDashboardRequest_VariableOverride) ProtoMessage() {}

func (x *LoadServiceDashboardRequest_VariableOverride) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_v1_dashboard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadServiceDashboardRequest_VariableOverride.ProtoReflect.Descriptor instead.
func (*LoadServiceDashboardRequest_VariableOverride) Descriptor() ([]byte, []int) {
	return file_grafana_v1_dashboard_proto_rawDescGZIP(), []int{4, 0}
}

func (x *LoadServiceDashboardRequest_VariableOverride) GetTemplateKey() string {
	if x != nil {
		return x.TemplateKey
	}
	return ""
}

func (x *LoadServiceDashboardRequest_VariableOverride) GetSubstitution() string {
	if x != nil {
		return x.Substitution
	}
	return ""
}

var File_grafana_v1_dashboard_proto protoreflect.FileDescriptor

const file_grafana_v1_dashboard_proto_rawDesc = "" +
	"\n" +
	"\x1agrafana/v1/dashboard.proto\x12\n" +
	"grafana.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x19grafana/v1/metadata.proto\"\xe3\x02\n" +
	"\x10ServiceDashboard\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tB\x03\xe0A\x03R\x05title\x12i\n" +
	"\x1agrafana_dashboard_document\x18\x03 \x01(\v2&.grafana.v1.GrafanaDashboardAccessMetaB\x03\xe0A\x03R\x18grafanaDashboardDocument:\xaf\x01\xeaA\xab\x01\n" +
	"3telemetry.the-protobuf-project.app/ServiceDashboard\x12OtelemetryWorkspaces/{telemetry_workspace}/serviceDashboards/{service_dashboard}*\x11serviceDashboards2\x10serviceDashboard\"\xd6\x01\n" +
	"\x1cListServiceDashboardsRequest\x12S\n" +
	"\x06parent\x18\x01 \x01(\tB;\xe0A\x02\xfaA5\x123telemetry.the-protobuf-project.app/ServiceDashboardR\x06parent\x12 \n" +
	"\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tB\x03\xe0A\x01R\tpageToken\x12\x1b\n" +
	"\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01R\x06filter\"\x94\x01\n" +
	"\x1dListServiceDashboardsResponse\x12K\n" +
	"\x12service_dashboards\x18\x01 \x03(\v2\x1c.grafana.v1.ServiceDashboardR\x11serviceDashboards\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"m\n" +
	"\x1aGetServiceDashboardRequest\x12O\n" +
	"\x04name\x18\x01 \x01(\tB;\xe0A\x02\xfaA5\n" +
	"3telemetry.the-protobuf-project.app/ServiceDashboardR\x04name\"\x9e\x04\n" +
	"\x1bLoadServiceDashboardRequest\x12O\n" +
	"\x04name\x18\x01 \x01(\tB;\xe0A\x02\xfaA5\n" +
	"3telemetry.the-protobuf-project.app/ServiceDashboardR\x04name\x12#\n" +
	"\x10time_range_start\x18\x02 \x01(\tB\x03\xe0A\x01R\x04from\x12\x1f\n" +
	"\x0etime_range_end\x18\x03 \x01(\tB\x03\xe0A\x01R\x02to\x12 \n" +
	"\ttime_zone\x18\x04 \x01(\tB\x03\xe0A\x01R\btimezone\x12l\n" +
	"\x12variable_overrides\x18\x05 \x03(\v28.grafana.v1.LoadServiceDashboardRequest.VariableOverrideB\x03\xe0A\x01R\x11variableOverrides\x121\n" +
	"\x12include_panel_data\x18\x06 \x01(\bB\x03\xe0A\x01R\x10includePanelData\x12$\n" +
	"\vgrafana_url\x18\a \x01(\tB\x03\xe0A\x01R\n" +
	"grafanaUrl\x12(\n" +
	"\rgrafana_token\x18\b \x01(\tB\x03\xe0A\x01R\fgrafanaToken\x1aU\n" +
	"\x10VariableOverride\x12\x1f\n" +
	"\ftemplate_key\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12 \n" +
	"\fsubstitution\x18\x02 \x01(\tB\x03\xe0A\x02R\x05value\"\x95\x03\n" +
	"\x1cLoadServiceDashboardResponse\x12I\n" +
	"\x11service_dashboard\x18\x01 \x01(\v2\x1c.grafana.v1.ServiceDashboardR\x10serviceDashboard\x12@\n" +
	"\x1aeffective_time_range_start\x18\x02 \x01(\tB\x03\xe0A\x03R\x17effectiveTimeRangeStart\x12<\n" +
	"\x18effective_time_range_end\x18\x03 \x01(\tB\x03\xe0A\x03R\x15effectiveTimeRangeEnd\x12h\n" +
	"\x0fpanel_data_json\x18\x04 \x03(\v2;.grafana.v1.LoadServiceDashboardResponse.PanelDataJsonEntryB\x03\xe0A\x03R\rpanelDataJson\x1a@\n" +
	"\x12PanelDataJsonEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x86\x01\n" +
	"\x0ecom.grafana.v1B\x0eDashboardProtoP\x01Zbgithub.com/the-protobuf-project/telemetry/telemetry-go/protobuf/grafana/v1/grafanapbv1;grafanapbv1b\x06proto3"

var (
	file_grafana_v1_dashboard_proto_rawDescOnce sync.Once
	file_grafana_v1_dashboard_proto_rawDescData []byte
)

func file_grafana_v1_dashboard_proto_rawDescGZIP() []byte {
	file_grafana_v1_dashboard_proto_rawDescOnce.Do(func() {
		file_grafana_v1_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grafana_v1_dashboard_proto_rawDesc), len(file_grafana_v1_dashboard_proto_rawDesc)))
	})
	return file_grafana_v1_dashboard_proto_rawDescData
}

var file_grafana_v1_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_grafana_v1_dashboard_proto_goTypes = []any{
	(*ServiceDashboard)(nil),                             // 0: grafana.v1.ServiceDashboard
	(*ListServiceDashboardsRequest)(nil),                 // 1: grafana.v1.ListServiceDashboardsRequest
	(*ListServiceDashboardsResponse)(nil),                // 2: grafana.v1.ListServiceDashboardsResponse
	(*GetServiceDashboardRequest)(nil),                   // 3: grafana.v1.GetServiceDashboardRequest
	(*LoadServiceDashboardRequest)(nil),                  // 4: grafana.v1.LoadServiceDashboardRequest
	(*LoadServiceDashboardResponse)(nil),                 // 5: grafana.v1.LoadServiceDashboardResponse
	(*LoadServiceDashboardRequest_VariableOverride)(nil), // 6: grafana.v1.LoadServiceDashboardRequest.VariableOverride
	nil,                                // 7: grafana.v1.LoadServiceDashboardResponse.PanelDataJsonEntry
	(*GrafanaDashboardAccessMeta)(nil), // 8: grafana.v1.GrafanaDashboardAccessMeta
}
var file_grafana_v1_dashboard_proto_depIdxs = []int32{
	8, // 0: grafana.v1.ServiceDashboard.grafana_dashboard_document:type_name -> grafana.v1.GrafanaDashboardAccessMeta
	0, // 1: grafana.v1.ListServiceDashboardsResponse.service_dashboards:type_name -> grafana.v1.ServiceDashboard
	6, // 2: grafana.v1.LoadServiceDashboardRequest.variable_overrides:type_name -> grafana.v1.LoadServiceDashboardRequest.VariableOverride
	0, // 3: grafana.v1.LoadServiceDashboardResponse.service_dashboard:type_name -> grafana.v1.ServiceDashboard
	7, // 4: grafana.v1.LoadServiceDashboardResponse.panel_data_json:type_name -> grafana.v1.LoadServiceDashboardResponse.PanelDataJsonEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_grafana_v1_dashboard_proto_init() }
func file_grafana_v1_dashboard_proto_init() {
	if File_grafana_v1_dashboard_proto != nil {
		return
	}
	file_grafana_v1_metadata_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grafana_v1_dashboard_proto_rawDesc), len(file_grafana_v1_dashboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grafana_v1_dashboard_proto_goTypes,
		DependencyIndexes: file_grafana_v1_dashboard_proto_depIdxs,
		MessageInfos:      file_grafana_v1_dashboard_proto_msgTypes,
	}.Build()
	File_grafana_v1_dashboard_proto = out.File
	file_grafana_v1_dashboard_proto_goTypes = nil
	file_grafana_v1_dashboard_proto_depIdxs = nil
}
