// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: grafana/v1/metadata.proto

// Grafana DashboardWithAccessInfo schema modelled for protobuf JSON round-trip.
//
// Design goals:
//   1. Every json_name matches the exact Grafana JSON key so protojson can
//      unmarshal dashboard.json with no normalisation step.
//   2. Fields that are deeply plugin-specific or opaque (vizConfig.spec,
//      queryOptions, transformations, variable spec) are google.protobuf.Struct
//      so nothing is lost.
//   3. All scalar booleans and integer defaults that Grafana always emits (e.g.
//      collapse:false, liveNow:false) are regular proto3 fields; callers must
//      marshal with EmitUnpopulated=true to reproduce those zero-value keys.
//
// go_package matches this file's real import path under telemetry-go so the
// generated stubs resolve for external consumers of the published BSR module.

package grafanapbv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Top-level Grafana DashboardWithAccessInfo object.
// JSON keys: apiVersion, kind, metadata, spec, status.
type GrafanaDashboardAccessMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// e.g. "dashboard.grafana.app/v2beta1"
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// e.g. "DashboardWithAccessInfo"
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Kubernetes-style object metadata.
	Metadata *GrafanaObjectMeta `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Dashboard body: panels, layout, variables, time settings, etc.
	Spec *GrafanaDashboardSpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	// Publication / access status from Grafana; often an empty object.
	Status        *structpb.Struct `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrafanaDashboardAccessMeta) Reset() {
	*x = GrafanaDashboardAccessMeta{}
	mi := &file_grafana_v1_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrafanaDashboardAccessMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrafanaDashboardAccessMeta) ProtoMessage() {}

func (x *GrafanaDashboardAccessMeta) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_v1_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrafanaDashboardAccessMeta.ProtoReflect.Descriptor instead.
func (*GrafanaDashboardAccessMeta) Descriptor() ([]byte, []int) {
	return file_grafana_v1_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *GrafanaDashboardAccessMeta) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *GrafanaDashboardAccessMeta) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GrafanaDashboardAccessMeta) GetMetadata() *GrafanaObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GrafanaDashboardAccessMeta) GetSpec() *GrafanaDashboardSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *GrafanaDashboardAccessMeta) GetStatus() *structpb.Struct {
	if x != nil {
		return x.Status
	}
	return nil
}

// Kubernetes-style metadata block (metadata.* in Grafana JSON).
// (-- api-linter: core::0123::resource-annotation=disabled
//
//	aip.dev/not-precedent: Mirrors Grafana object metadata; not a standalone API resource. --)
type GrafanaObjectMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Grafana resource name within its namespace.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Kubernetes namespace (typically "default").
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// ULID stable object identifier.
	Id string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	// Opaque optimistic-concurrency version string (JSON: "resourceVersion").
	ResourceVersion string `protobuf:"bytes,4,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	// Monotonic generation counter. Grafana JSON emits this as a number.
	Generation int64 `protobuf:"varint,5,opt,name=generation,proto3" json:"generation,omitempty"`
	// RFC 3339 creation time string (JSON: "creationTimestamp").
	// Stored as string to match Grafana's plain RFC 3339 text (not protobuf Timestamp JSON).
	// (-- api-linter: core::0142::time-field-type=disabled
	//
	//	aip.dev/not-precedent: Grafana emits a plain RFC 3339 string, not Timestamp JSON. --)
	CreationTimestamp string `protobuf:"bytes,6,opt,name=creation_timestamp,json=creationTimestamp,proto3" json:"creation_timestamp,omitempty"`
	// Internal Grafana labels (e.g. deprecatedInternalID).
	Labels map[string]string `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Internal Grafana annotations (e.g. createdBy, folder, saved-from-ui).
	Annotations   map[string]string `protobuf:"bytes,8,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrafanaObjectMeta) Reset() {
	*x = GrafanaObjectMeta{}
	mi := &file_grafana_v1_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrafanaObjectMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrafanaObjectMeta) ProtoMessage() {}

func (x *GrafanaObjectMeta) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_v1_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrafanaObjectMeta.ProtoReflect.Descriptor instead.
func (*GrafanaObjectMeta) Descriptor() ([]byte, []int) {
	return file_grafana_v1_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *GrafanaObjectMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GrafanaObjectMeta) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GrafanaObjectMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GrafanaObjectMeta) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

func (x *GrafanaObjectMeta) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *GrafanaObjectMeta) GetCreationTimestamp() string {
	if x != nil {
		return x.CreationTimestamp
	}
	return ""
}

func (x *GrafanaObjectMeta) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *GrafanaObjectMeta) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

// Everything under dashboard.json "spec".
type GrafanaDashboardSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Annotation query layers shown in the dashboard header.
	Annotations []*GrafanaAnnotationItem `protobuf:"bytes,1,rep,name=annotations,proto3" json:"annotations,omitempty"`
	// Cross-panel cursor sync mode (JSON: "cursorSync"). e.g. "Off", "Crosshair", "Tooltip".
	CursorSync string `protobuf:"bytes,2,opt,name=cursor_sync,json=cursorSync,proto3" json:"cursor_sync,omitempty"`
	// Whether the dashboard is editable in the Grafana UI.
	Editable bool `protobuf:"varint,3,opt,name=editable,proto3" json:"editable,omitempty"`
	// Panels keyed by element id (e.g. "panel-12"). JSON: "elements".
	Elements map[string]*GrafanaPanelElement `protobuf:"bytes,4,rep,name=elements,proto3" json:"elements,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Root layout tree (RowsLayout, GridLayout, …).
	Layout *GrafanaLayout `protobuf:"bytes,5,opt,name=layout,proto3" json:"layout,omitempty"`
	// Dashboard header links.
	Links []*structpb.Struct `protobuf:"bytes,6,rep,name=links,proto3" json:"links,omitempty"`
	// When true, enables live "now" scrolling (JSON: "liveNow").
	LiveNow bool `protobuf:"varint,7,opt,name=live_now,json=liveNow,proto3" json:"live_now,omitempty"`
	// When true, preloads all panels eagerly.
	Preload bool `protobuf:"varint,8,opt,name=preload,proto3" json:"preload,omitempty"`
	// Searchable dashboard tags.
	Tags []string `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	// Default time range and refresh settings (JSON: "timeSettings").
	TimeSettings *GrafanaTimeSettings `protobuf:"bytes,10,opt,name=time_settings,json=timeSettings,proto3" json:"time_settings,omitempty"`
	// Dashboard display title.
	Title string `protobuf:"bytes,11,opt,name=title,proto3" json:"title,omitempty"`
	// Template variables (QueryVariable, ConstantVariable, …).
	Variables     []*GrafanaVariableItem `protobuf:"bytes,12,rep,name=variables,proto3" json:"variables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrafanaDashboardSpec) Reset() {
	*x = GrafanaDashboardSpec{}
	mi := &file_grafana_v1_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrafanaDashboardSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrafanaDashboardSpec) ProtoMessage() {}

func (x *GrafanaDashboardSpec) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_v1_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrafanaDashboardSpec.ProtoReflect.Descriptor instead.
func (*GrafanaDashboardSpec) Descriptor() ([]byte, []int) {
	return file_grafana_v1_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *GrafanaDashboardSpec) GetAnnotations() []*GrafanaAnnotationItem {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *GrafanaDashboardSpec) GetCursorSync() string {
	if x != nil {
		return x.CursorSync
	}
	return ""
}

func (x *GrafanaDashboardSpec) GetEditable() bool {
	if x != nil {
		return x.Editable
	}
	return false
}

func (x *GrafanaDashboardSpec) GetElements() map[string]*GrafanaPanelElement {
	if x != nil {
		return x.Elements
	}
	return nil
}

func (x *GrafanaDashboardSpec) GetLayout() *GrafanaLayout {
	if x != nil {
		return x.Layout
	}
	return nil
}

func (x *GrafanaDashboardSpec) GetLinks() []*structpb.Struct {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *GrafanaDashboardSpec) GetLiveNow() bool {
	if x != nil {
		return x.LiveNow
	}
	return false
}

func (x *GrafanaDashboardSpec) GetPreload() bool {
	if x != nil {
		return x.Preload
	}
	return false
}

func (x *GrafanaDashboardSpec) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *GrafanaDashboardSpec) GetTimeSettings() *GrafanaTimeSettings {
	if x != nil {
		return x.TimeSettings
	}
	return nil
}

func (x *GrafanaDashboardSpec) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GrafanaDashboardSpec) GetVariables() []*GrafanaVariableItem {
	if x != nil {
		return x.Variables
	}
	return nil
}

// One entry in spec.annotations[].
type GrafanaAnnotationItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// e.g. "AnnotationQuery"
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Annotation row body.
	Spec          *GrafanaAnnotationSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrafanaAnnotationItem) Reset() {
	*x = GrafanaAnnotationItem{}
	mi := &file_grafana_v1_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrafanaAnnotationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrafanaAnnotationItem) ProtoMessage() {}

func (x *GrafanaAnnotationItem) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_v1_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrafanaAnnotationItem.ProtoReflect.Descriptor instead.
func (*GrafanaAnnotationItem) Descriptor() ([]byte, []int) {
	return file_grafana_v1_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *GrafanaAnnotationItem) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GrafanaAnnotationItem) GetSpec() *GrafanaAnnotationSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// Body of an AnnotationQuery annotation (spec.annotations[].spec).
// (-- api-linter: core::0123::resource-annotation=disabled
//
//	aip.dev/not-precedent: Nested Grafana spec; `name` is a display label, not a resource name. --)
type GrafanaAnnotationSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when this is a built-in Grafana annotation layer (JSON: "builtIn").
	// (-- api-linter: core::0140::prepositions=disabled
	//
	//	aip.dev/not-precedent: Field name matches Grafana `builtIn` via json_name. --)
	BuiltIn bool `protobuf:"varint,1,opt,name=built_in,json=builtIn,proto3" json:"built_in,omitempty"`
	// Whether the annotation layer is enabled.
	Enable bool `protobuf:"varint,2,opt,name=enable,proto3" json:"enable,omitempty"`
	// Whether the layer is hidden from the UI toggles.
	Hide bool `protobuf:"varint,3,opt,name=hide,proto3" json:"hide,omitempty"`
	// Marker colour string (JSON: "iconColor").
	IconColor string `protobuf:"bytes,4,opt,name=icon_color,json=iconColor,proto3" json:"icon_color,omitempty"`
	// Human-readable annotation layer name.
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	// Full Grafana DataQuery envelope; opaque Struct for plugin compatibility.
	Query         *structpb.Struct `protobuf:"bytes,6,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrafanaAnnotationSpec) Reset() {
	*x = GrafanaAnnotationSpec{}
	mi := &file_grafana_v1_metadata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrafanaAnnotationSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrafanaAnnotationSpec) ProtoMessage() {}

func (x *GrafanaAnnotationSpec) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_v1_metadata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrafanaAnnotationSpec.ProtoReflect.Descriptor instead.
func (*GrafanaAnnotationSpec) Descriptor() ([]byte, []int) {
	return file_grafana_v1_metadata_proto_rawDescGZIP(), []int{4}
}

func (x *GrafanaAnnotationSpec) GetBuiltIn() bool {
	if x != nil {
		return x.BuiltIn
	}
	return false
}

func (x *GrafanaAnnotationSpec) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *GrafanaAnnotationSpec) GetHide() bool {
	if x != nil {
		return x.Hide
	}
	return false
}

func (x *GrafanaAnnotationSpec) GetIconColor() string {
	if x != nil {
		return x.IconColor
	}
	return ""
}

func (x *GrafanaAnnotationSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GrafanaAnnotationSpec) GetQuery() *structpb.Struct {
	if x != nil {
		return x.Query
	}
	return nil
}

// One value in spec.elements: {kind, spec}.
type GrafanaPanelElement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "Panel" or "LibraryPanel"
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Full panel body (data, description, id, links, title, vizConfig).
	Spec          *GrafanaPanelSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrafanaPanelElement) Reset() {
	*x = GrafanaPanelElement{}
	mi := &file_grafana_v1_metadata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrafanaPanelElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrafanaPanelElement) ProtoMessage() {}

func (x *GrafanaPanelElement) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_v1_metadata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrafanaPanelElement.ProtoReflect.Descriptor instead.
func (*GrafanaPanelElement) Descriptor() ([]byte, []int) {
	return file_grafana_v1_metadata_proto_rawDescGZIP(), []int{5}
}

func (x *GrafanaPanelElement) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GrafanaPanelElement) GetSpec() *GrafanaPanelSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// Body under elements.*.spec for a Panel element.
type GrafanaPanelSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Query group (queries, transformations, queryOptions).
	Data *GrafanaQueryGroup `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Subtitle / description text.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Numeric Grafana panel id.
	Id int32 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	// Panel-level drilldown links (opaque Struct array).
	Links []*structpb.Struct `protobuf:"bytes,4,rep,name=links,proto3" json:"links,omitempty"`
	// Panel title.
	Title string `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	// Visualisation config wrapper (JSON: "vizConfig").
	VizConfig     *GrafanaVizConfig `protobuf:"bytes,6,opt,name=viz_config,json=vizConfig,proto3" json:"viz_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrafanaPanelSpec) Reset() {
	*x = GrafanaPanelSpec{}
	mi := &file_grafana_v1_metadata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrafanaPanelSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrafanaPanelSpec) ProtoMessage() {}

func (x *GrafanaPanelSpec) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_v1_metadata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrafanaPanelSpec.ProtoReflect.Descriptor instead.
func (*GrafanaPanelSpec) Descriptor() ([]byte, []int) {
	return file_grafana_v1_metadata_proto_rawDescGZIP(), []int{6}
}

func (x *GrafanaPanelSpec) GetData() *GrafanaQueryGroup {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GrafanaPanelSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GrafanaPanelSpec) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GrafanaPanelSpec) GetLinks() []*structpb.Struct {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *GrafanaPanelSpec) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GrafanaPanelSpec) GetVizConfig() *GrafanaVizConfig {
	if x != nil {
		return x.VizConfig
	}
	return nil
}

// Wrapper for a Grafana QueryGroup (data.kind + data.spec).
type GrafanaQueryGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// e.g. "QueryGroup"
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Query group body.
	Spec          *GrafanaQueryGroupSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrafanaQueryGroup) Reset() {
	*x = GrafanaQueryGroup{}
	mi := &file_grafana_v1_metadata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrafanaQueryGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrafanaQueryGroup) ProtoMessage() {}

func (x *GrafanaQueryGroup) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_v1_metadata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrafanaQueryGroup.ProtoReflect.Descriptor instead.
func (*GrafanaQueryGroup) Descriptor() ([]byte, []int) {
	return file_grafana_v1_metadata_proto_rawDescGZIP(), []int{7}
}

func (x *GrafanaQueryGroup) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GrafanaQueryGroup) GetSpec() *GrafanaQueryGroupSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// Inner body of a QueryGroup (spec.queries, spec.queryOptions, spec.transformations).
type GrafanaQueryGroupSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Panel query rows.
	Queries []*GrafanaPanelQueryItem `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	// Shared query options (maxDataPoints, interval, …); opaque Struct.
	QueryOptions *structpb.Struct `protobuf:"bytes,2,opt,name=query_options,json=queryOptions,proto3" json:"query_options,omitempty"`
	// Transformation pipeline steps; each step is opaque Struct.
	Transformations []*structpb.Struct `protobuf:"bytes,3,rep,name=transformations,proto3" json:"transformations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GrafanaQueryGroupSpec) Reset() {
	*x = GrafanaQueryGroupSpec{}
	mi := &file_grafana_v1_metadata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrafanaQueryGroupSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrafanaQueryGroupSpec) ProtoMessage() {}

func (x *GrafanaQueryGroupSpec) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_v1_metadata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrafanaQueryGroupSpec.ProtoReflect.Descriptor instead.
func (*GrafanaQueryGroupSpec) Descriptor() ([]byte, []int) {
	return file_grafana_v1_metadata_proto_rawDescGZIP(), []int{8}
}

func (x *GrafanaQueryGroupSpec) GetQueries() []*GrafanaPanelQueryItem {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *GrafanaQueryGroupSpec) GetQueryOptions() *structpb.Struct {
	if x != nil {
		return x.QueryOptions
	}
	return nil
}

func (x *GrafanaQueryGroupSpec) GetTransformations() []*structpb.Struct {
	if x != nil {
		return x.Transformations
	}
	return nil
}

// One slot in queries[]: {kind:"PanelQuery", spec:{…}}.
type GrafanaPanelQueryItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// e.g. "PanelQuery"
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Query row body.
	Spec          *GrafanaPanelQuerySpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrafanaPanelQueryItem) Reset() {
	*x = GrafanaPanelQueryItem{}
	mi := &file_grafana_v1_metadata_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrafanaPanelQueryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrafanaPanelQueryItem) ProtoMessage() {}

func (x *GrafanaPanelQueryItem) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_v1_metadata_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrafanaPanelQueryItem.ProtoReflect.Descriptor instead.
func (*GrafanaPanelQueryItem) Descriptor() ([]byte, []int) {
	return file_grafana_v1_metadata_proto_rawDescGZIP(), []int{9}
}

func (x *GrafanaPanelQueryItem) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GrafanaPanelQueryItem) GetSpec() *GrafanaPanelQuerySpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// Inner spec for a PanelQuery row.
type GrafanaPanelQuerySpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When true, the query is hidden in the editor.
	Hidden bool `protobuf:"varint,1,opt,name=hidden,proto3" json:"hidden,omitempty"`
	// Grafana DataQuery envelope.
	Query *GrafanaDataQuery `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// Query reference id (e.g. "A", "B").
	RefId         string `protobuf:"bytes,3,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrafanaPanelQuerySpec) Reset() {
	*x = GrafanaPanelQuerySpec{}
	mi := &file_grafana_v1_metadata_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrafanaPanelQuerySpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrafanaPanelQuerySpec) ProtoMessage() {}

func (x *GrafanaPanelQuerySpec) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_v1_metadata_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrafanaPanelQuerySpec.ProtoReflect.Descriptor instead.
func (*GrafanaPanelQuerySpec) Descriptor() ([]byte, []int) {
	return file_grafana_v1_metadata_proto_rawDescGZIP(), []int{10}
}

func (x *GrafanaPanelQuerySpec) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *GrafanaPanelQuerySpec) GetQuery() *GrafanaDataQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *GrafanaPanelQuerySpec) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

// Grafana DataQuery envelope: datasource selector, group, plugin spec, version.
type GrafanaDataQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Datasource reference.
	Datasource *GrafanaDatasourceRef `protobuf:"bytes,1,opt,name=datasource,proto3" json:"datasource,omitempty"`
	// Plugin group (e.g. "prometheus", "loki", "tempo", "grafana").
	Group string `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	// e.g. "DataQuery"
	Kind string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	// Plugin-specific query body; opaque Struct (editorMode, expr, filters, …).
	Spec *structpb.Struct `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	// Schema version string (e.g. "v0").
	Version       string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrafanaDataQuery) Reset() {
	*x = GrafanaDataQuery{}
	mi := &file_grafana_v1_metadata_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrafanaDataQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrafanaDataQuery) ProtoMessage() {}

func (x *GrafanaDataQuery) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_v1_metadata_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrafanaDataQuery.ProtoReflect.Descriptor instead.
func (*GrafanaDataQuery) Descriptor() ([]byte, []int) {
	return file_grafana_v1_metadata_proto_rawDescGZIP(), []int{11}
}

func (x *GrafanaDataQuery) GetDatasource() *GrafanaDatasourceRef {
	if x != nil {
		return x.Datasource
	}
	return nil
}

func (x *GrafanaDataQuery) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GrafanaDataQuery) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GrafanaDataQuery) GetSpec() *structpb.Struct {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *GrafanaDataQuery) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Datasource selector embedded in DataQuery.
// (-- api-linter: core::0123::resource-annotation=disabled
//
//	aip.dev/not-precedent: Grafana datasource pointer; `name` is not a google.api.resource name. --)
type GrafanaDatasourceRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Named datasource (e.g. "prometheus", "loki", "tempo", "-- Grafana --").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Datasource plugin type (e.g. "prometheus"). Present on some exports.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Instance UID or sentinel "$__default". JSON key "uid".
	// (-- api-linter: core::0148::uid-format=disabled
	//
	//	aip.dev/not-precedent: Value may be $__default, not a ULID. --)
	Uid           string `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrafanaDatasourceRef) Reset() {
	*x = GrafanaDatasourceRef{}
	mi := &file_grafana_v1_metadata_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrafanaDatasourceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrafanaDatasourceRef) ProtoMessage() {}

func (x *GrafanaDatasourceRef) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_v1_metadata_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrafanaDatasourceRef.ProtoReflect.Descriptor instead.
func (*GrafanaDatasourceRef) Descriptor() ([]byte, []int) {
	return file_grafana_v1_metadata_proto_rawDescGZIP(), []int{12}
}

func (x *GrafanaDatasourceRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GrafanaDatasourceRef) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GrafanaDatasourceRef) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// Visualisation config wrapper (vizConfig.group, kind, spec, version).
type GrafanaVizConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Plugin group (e.g. "timeseries", "stat", "piechart", "table", "logs").
	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	// e.g. "VizConfig"
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Plugin-specific fieldConfig + options; opaque Struct.
	Spec *structpb.Struct `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	// Grafana version that saved this config (e.g. "12.4.1").
	Version       string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrafanaVizConfig) Reset() {
	*x = GrafanaVizConfig{}
	mi := &file_grafana_v1_metadata_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrafanaVizConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrafanaVizConfig) ProtoMessage() {}

func (x *GrafanaVizConfig) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_v1_metadata_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrafanaVizConfig.ProtoReflect.Descriptor instead.
func (*GrafanaVizConfig) Descriptor() ([]byte, []int) {
	return file_grafana_v1_metadata_proto_rawDescGZIP(), []int{13}
}

func (x *GrafanaVizConfig) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GrafanaVizConfig) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GrafanaVizConfig) GetSpec() *structpb.Struct {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *GrafanaVizConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Root layout node: {kind, spec}.
type GrafanaLayout struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// e.g. "RowsLayout", "GridLayout", "AutoGridLayout"
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Layout body.
	Spec          *GrafanaLayoutSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrafanaLayout) Reset() {
	*x = GrafanaLayout{}
	mi := &file_grafana_v1_metadata_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrafanaLayout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrafanaLayout) ProtoMessage() {}

func (x *GrafanaLayout) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_v1_metadata_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrafanaLayout.ProtoReflect.Descriptor instead.
func (*GrafanaLayout) Descriptor() ([]byte, []int) {
	return file_grafana_v1_metadata_proto_rawDescGZIP(), []int{14}
}

func (x *GrafanaLayout) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GrafanaLayout) GetSpec() *GrafanaLayoutSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// Body of a layout spec. Only one branch is populated depending on kind.
type GrafanaLayoutSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RowsLayout rows.
	Rows []*GrafanaRowsLayoutRow `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	// GridLayout items.
	Items         []*GrafanaGridLayoutItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrafanaLayoutSpec) Reset() {
	*x = GrafanaLayoutSpec{}
	mi := &file_grafana_v1_metadata_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrafanaLayoutSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrafanaLayoutSpec) ProtoMessage() {}

func (x *GrafanaLayoutSpec) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_v1_metadata_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrafanaLayoutSpec.ProtoReflect.Descriptor instead.
func (*GrafanaLayoutSpec) Descriptor() ([]byte, []int) {
	return file_grafana_v1_metadata_proto_rawDescGZIP(), []int{15}
}

func (x *GrafanaLayoutSpec) GetRows() []*GrafanaRowsLayoutRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *GrafanaLayoutSpec) GetItems() []*GrafanaGridLayoutItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// One row in a RowsLayout.
type GrafanaRowsLayoutRow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// e.g. "RowsLayoutRow"
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Row body.
	Spec          *GrafanaRowsLayoutRowSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrafanaRowsLayoutRow) Reset() {
	*x = GrafanaRowsLayoutRow{}
	mi := &file_grafana_v1_metadata_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrafanaRowsLayoutRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrafanaRowsLayoutRow) ProtoMessage() {}

func (x *GrafanaRowsLayoutRow) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_v1_metadata_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrafanaRowsLayoutRow.ProtoReflect.Descriptor instead.
func (*GrafanaRowsLayoutRow) Descriptor() ([]byte, []int) {
	return file_grafana_v1_metadata_proto_rawDescGZIP(), []int{16}
}

func (x *GrafanaRowsLayoutRow) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GrafanaRowsLayoutRow) GetSpec() *GrafanaRowsLayoutRowSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// Inner spec for a RowsLayoutRow.
type GrafanaRowsLayoutRowSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the row starts collapsed.
	Collapse bool `protobuf:"varint,1,opt,name=collapse,proto3" json:"collapse,omitempty"`
	// Nested layout (typically a GridLayout).
	Layout *GrafanaLayout `protobuf:"bytes,2,opt,name=layout,proto3" json:"layout,omitempty"`
	// Row section title displayed in the dashboard.
	Title         string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrafanaRowsLayoutRowSpec) Reset() {
	*x = GrafanaRowsLayoutRowSpec{}
	mi := &file_grafana_v1_metadata_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrafanaRowsLayoutRowSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrafanaRowsLayoutRowSpec) ProtoMessage() {}

func (x *GrafanaRowsLayoutRowSpec) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_v1_metadata_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrafanaRowsLayoutRowSpec.ProtoReflect.Descriptor instead.
func (*GrafanaRowsLayoutRowSpec) Descriptor() ([]byte, []int) {
	return file_grafana_v1_metadata_proto_rawDescGZIP(), []int{17}
}

func (x *GrafanaRowsLayoutRowSpec) GetCollapse() bool {
	if x != nil {
		return x.Collapse
	}
	return false
}

func (x *GrafanaRowsLayoutRowSpec) GetLayout() *GrafanaLayout {
	if x != nil {
		return x.Layout
	}
	return nil
}

func (x *GrafanaRowsLayoutRowSpec) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

// One item in a GridLayout.
type GrafanaGridLayoutItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// e.g. "GridLayoutItem"
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Grid item body.
	Spec          *GrafanaGridLayoutItemSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrafanaGridLayoutItem) Reset() {
	*x = GrafanaGridLayoutItem{}
	mi := &file_grafana_v1_metadata_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrafanaGridLayoutItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrafanaGridLayoutItem) ProtoMessage() {}

func (x *GrafanaGridLayoutItem) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_v1_metadata_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrafanaGridLayoutItem.ProtoReflect.Descriptor instead.
func (*GrafanaGridLayoutItem) Descriptor() ([]byte, []int) {
	return file_grafana_v1_metadata_proto_rawDescGZIP(), []int{18}
}

func (x *GrafanaGridLayoutItem) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GrafanaGridLayoutItem) GetSpec() *GrafanaGridLayoutItemSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// Position and element reference for a grid layout item.
type GrafanaGridLayoutItemSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reference to a panel in spec.elements.
	Element *GrafanaElementReference `protobuf:"bytes,1,opt,name=element,proto3" json:"element,omitempty"`
	// Height in grid units.
	Height int32 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	// Width in grid units.
	Width int32 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	// Column origin (0-based).
	X int32 `protobuf:"varint,4,opt,name=x,proto3" json:"x,omitempty"`
	// Row origin (0-based).
	Y             int32 `protobuf:"varint,5,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrafanaGridLayoutItemSpec) Reset() {
	*x = GrafanaGridLayoutItemSpec{}
	mi := &file_grafana_v1_metadata_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrafanaGridLayoutItemSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrafanaGridLayoutItemSpec) ProtoMessage() {}

func (x *GrafanaGridLayoutItemSpec) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_v1_metadata_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrafanaGridLayoutItemSpec.ProtoReflect.Descriptor instead.
func (*GrafanaGridLayoutItemSpec) Descriptor() ([]byte, []int) {
	return file_grafana_v1_metadata_proto_rawDescGZIP(), []int{19}
}

func (x *GrafanaGridLayoutItemSpec) GetElement() *GrafanaElementReference {
	if x != nil {
		return x.Element
	}
	return nil
}

func (x *GrafanaGridLayoutItemSpec) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *GrafanaGridLayoutItemSpec) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *GrafanaGridLayoutItemSpec) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *GrafanaGridLayoutItemSpec) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Pointer to an entry in spec.elements.
// (-- api-linter: core::0123::resource-annotation=disabled
//
//	aip.dev/not-precedent: Element key reference; not a top-level API resource. --)
type GrafanaElementReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// e.g. "ElementReference"
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Key into the elements map (e.g. "panel-12").
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrafanaElementReference) Reset() {
	*x = GrafanaElementReference{}
	mi := &file_grafana_v1_metadata_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrafanaElementReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrafanaElementReference) ProtoMessage() {}

func (x *GrafanaElementReference) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_v1_metadata_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrafanaElementReference.ProtoReflect.Descriptor instead.
func (*GrafanaElementReference) Descriptor() ([]byte, []int) {
	return file_grafana_v1_metadata_proto_rawDescGZIP(), []int{20}
}

func (x *GrafanaElementReference) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GrafanaElementReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// spec.timeSettings block.
// (-- api-linter: core::0140::prepositions=disabled
//
//	aip.dev/not-precedent: `from`/`to` mirror Grafana timeSettings JSON keys. --)
//
// (-- api-linter: core::0140::reserved-words=disabled
//
//	aip.dev/not-precedent: Grafana JSON key `from` mapped via json_name. --)
//
// (-- api-linter: core::0143::standardized-codes=disabled
//
//	aip.dev/not-precedent: Grafana uses `timezone`; proto field matches that key. --)
type GrafanaTimeSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Auto-refresh interval string; empty disables refresh (JSON: "autoRefresh").
	AutoRefresh string `protobuf:"bytes,1,opt,name=auto_refresh,json=autoRefresh,proto3" json:"auto_refresh,omitempty"`
	// Preset intervals shown in the UI refresh picker (JSON: "autoRefreshIntervals").
	AutoRefreshIntervals []string `protobuf:"bytes,2,rep,name=auto_refresh_intervals,json=autoRefreshIntervals,proto3" json:"auto_refresh_intervals,omitempty"`
	// Fiscal year start month 0–11; 0 = calendar year (JSON: "fiscalYearStartMonth").
	FiscalYearStartMonth int32 `protobuf:"varint,3,opt,name=fiscal_year_start_month,json=fiscalYearStartMonth,proto3" json:"fiscal_year_start_month,omitempty"`
	// Default range start; Grafana relative or RFC 3339 (JSON: "from").
	From string `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	// When true, the time picker toolbar is hidden (JSON: "hideTimepicker").
	HideTimepicker bool `protobuf:"varint,5,opt,name=hide_timepicker,json=hideTimepicker,proto3" json:"hide_timepicker,omitempty"`
	// IANA timezone id or "browser" (JSON: "timezone").
	Timezone string `protobuf:"bytes,6,opt,name=timezone,proto3" json:"timezone,omitempty"`
	// Default range end (JSON: "to").
	To            string `protobuf:"bytes,7,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrafanaTimeSettings) Reset() {
	*x = GrafanaTimeSettings{}
	mi := &file_grafana_v1_metadata_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrafanaTimeSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrafanaTimeSettings) ProtoMessage() {}

func (x *GrafanaTimeSettings) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_v1_metadata_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrafanaTimeSettings.ProtoReflect.Descriptor instead.
func (*GrafanaTimeSettings) Descriptor() ([]byte, []int) {
	return file_grafana_v1_metadata_proto_rawDescGZIP(), []int{21}
}

func (x *GrafanaTimeSettings) GetAutoRefresh() string {
	if x != nil {
		return x.AutoRefresh
	}
	return ""
}

func (x *GrafanaTimeSettings) GetAutoRefreshIntervals() []string {
	if x != nil {
		return x.AutoRefreshIntervals
	}
	return nil
}

func (x *GrafanaTimeSettings) GetFiscalYearStartMonth() int32 {
	if x != nil {
		return x.FiscalYearStartMonth
	}
	return 0
}

func (x *GrafanaTimeSettings) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *GrafanaTimeSettings) GetHideTimepicker() bool {
	if x != nil {
		return x.HideTimepicker
	}
	return false
}

func (x *GrafanaTimeSettings) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *GrafanaTimeSettings) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

// One template variable entry (QueryVariable, ConstantVariable, …).
// The spec is opaque Struct because variable bodies differ significantly by kind.
type GrafanaVariableItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// e.g. "QueryVariable", "ConstantVariable", "TextboxVariable"
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Full variable body (allowCustomValue, current, definition, hide, …).
	Spec          *structpb.Struct `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrafanaVariableItem) Reset() {
	*x = GrafanaVariableItem{}
	mi := &file_grafana_v1_metadata_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrafanaVariableItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrafanaVariableItem) ProtoMessage() {}

func (x *GrafanaVariableItem) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_v1_metadata_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrafanaVariableItem.ProtoReflect.Descriptor instead.
func (*GrafanaVariableItem) Descriptor() ([]byte, []int) {
	return file_grafana_v1_metadata_proto_rawDescGZIP(), []int{22}
}

func (x *GrafanaVariableItem) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GrafanaVariableItem) GetSpec() *structpb.Struct {
	if x != nil {
		return x.Spec
	}
	return nil
}

var File_grafana_v1_metadata_proto protoreflect.FileDescriptor

const file_grafana_v1_metadata_proto_rawDesc = "" +
	"\n" +
	"\x19grafana/v1/metadata.proto\x12\n" +
	"grafana.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x8c\x02\n" +
	"\x1aGrafanaDashboardAccessMeta\x12$\n" +
	"\vapi_version\x18\x01 \x01(\tB\x03\xe0A\x03R\n" +
	"apiVersion\x12\x17\n" +
	"\x04kind\x18\x02 \x01(\tB\x03\xe0A\x03R\x04kind\x12>\n" +
	"\bmetadata\x18\x03 \x01(\v2\x1d.grafana.v1.GrafanaObjectMetaB\x03\xe0A\x03R\bmetadata\x129\n" +
	"\x04spec\x18\x04 \x01(\v2 .grafana.v1.GrafanaDashboardSpecB\x03\xe0A\x03R\x04spec\x124\n" +
	"\x06status\x18\x05 \x01(\v2\x17.google.protobuf.StructB\x03\xe0A\x03R\x06status\"\x87\x04\n" +
	"\x11GrafanaObjectMeta\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x03R\x04name\x12!\n" +
	"\tnamespace\x18\x02 \x01(\tB\x03\xe0A\x03R\tnamespace\x12\x13\n" +
	"\x02id\x18\x03 \x01(\tB\x03\xe0A\x03R\x02id\x12.\n" +
	"\x10resource_version\x18\x04 \x01(\tB\x03\xe0A\x03R\x0fresourceVersion\x12#\n" +
	"\n" +
	"generation\x18\x05 \x01(\x03B\x03\xe0A\x03R\n" +
	"generation\x122\n" +
	"\x12creation_timestamp\x18\x06 \x01(\tB\x03\xe0A\x03R\x11creationTimestamp\x12F\n" +
	"\x06labels\x18\a \x03(\v2).grafana.v1.GrafanaObjectMeta.LabelsEntryB\x03\xe0A\x03R\x06labels\x12U\n" +
	"\vannotations\x18\b \x03(\v2..grafana.v1.GrafanaObjectMeta.AnnotationsEntryB\x03\xe0A\x03R\vannotations\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc4\x05\n" +
	"\x14GrafanaDashboardSpec\x12H\n" +
	"\vannotations\x18\x01 \x03(\v2!.grafana.v1.GrafanaAnnotationItemB\x03\xe0A\x01R\vannotations\x12$\n" +
	"\vcursor_sync\x18\x02 \x01(\tB\x03\xe0A\x01R\n" +
	"cursorSync\x12\x1f\n" +
	"\beditable\x18\x03 \x01(\bB\x03\xe0A\x01R\beditable\x12O\n" +
	"\belements\x18\x04 \x03(\v2..grafana.v1.GrafanaDashboardSpec.ElementsEntryB\x03\xe0A\x01R\belements\x126\n" +
	"\x06layout\x18\x05 \x01(\v2\x19.grafana.v1.GrafanaLayoutB\x03\xe0A\x01R\x06layout\x122\n" +
	"\x05links\x18\x06 \x03(\v2\x17.google.protobuf.StructB\x03\xe0A\x01R\x05links\x12\x1e\n" +
	"\blive_now\x18\a \x01(\bB\x03\xe0A\x01R\aliveNow\x12\x1d\n" +
	"\apreload\x18\b \x01(\bB\x03\xe0A\x01R\apreload\x12\x17\n" +
	"\x04tags\x18\t \x03(\tB\x03\xe0A\x01R\x04tags\x12I\n" +
	"\rtime_settings\x18\n" +
	" \x01(\v2\x1f.grafana.v1.GrafanaTimeSettingsB\x03\xe0A\x01R\ftimeSettings\x12\x19\n" +
	"\x05title\x18\v \x01(\tB\x03\xe0A\x01R\x05title\x12B\n" +
	"\tvariables\x18\f \x03(\v2\x1f.grafana.v1.GrafanaVariableItemB\x03\xe0A\x01R\tvariables\x1a\\\n" +
	"\rElementsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.grafana.v1.GrafanaPanelElementR\x05value:\x028\x01\"l\n" +
	"\x15GrafanaAnnotationItem\x12\x17\n" +
	"\x04kind\x18\x01 \x01(\tB\x03\xe0A\x01R\x04kind\x12:\n" +
	"\x04spec\x18\x02 \x01(\v2!.grafana.v1.GrafanaAnnotationSpecB\x03\xe0A\x01R\x04spec\"\xde\x01\n" +
	"\x15GrafanaAnnotationSpec\x12\x1e\n" +
	"\bbuilt_in\x18\x01 \x01(\bB\x03\xe0A\x01R\abuiltIn\x12\x1b\n" +
	"\x06enable\x18\x02 \x01(\bB\x03\xe0A\x01R\x06enable\x12\x17\n" +
	"\x04hide\x18\x03 \x01(\bB\x03\xe0A\x01R\x04hide\x12\"\n" +
	"\n" +
	"icon_color\x18\x04 \x01(\tB\x03\xe0A\x01R\ticonColor\x12\x17\n" +
	"\x04name\x18\x05 \x01(\tB\x03\xe0A\x01R\x04name\x122\n" +
	"\x05query\x18\x06 \x01(\v2\x17.google.protobuf.StructB\x03\xe0A\x01R\x05query\"e\n" +
	"\x13GrafanaPanelElement\x12\x17\n" +
	"\x04kind\x18\x01 \x01(\tB\x03\xe0A\x01R\x04kind\x125\n" +
	"\x04spec\x18\x02 \x01(\v2\x1c.grafana.v1.GrafanaPanelSpecB\x03\xe0A\x01R\x04spec\"\x97\x02\n" +
	"\x10GrafanaPanelSpec\x126\n" +
	"\x04data\x18\x01 \x01(\v2\x1d.grafana.v1.GrafanaQueryGroupB\x03\xe0A\x01R\x04data\x12%\n" +
	"\vdescription\x18\x02 \x01(\tB\x03\xe0A\x01R\vdescription\x12\x13\n" +
	"\x02id\x18\x03 \x01(\x05B\x03\xe0A\x01R\x02id\x122\n" +
	"\x05links\x18\x04 \x03(\v2\x17.google.protobuf.StructB\x03\xe0A\x01R\x05links\x12\x19\n" +
	"\x05title\x18\x05 \x01(\tB\x03\xe0A\x01R\x05title\x12@\n" +
	"\n" +
	"viz_config\x18\x06 \x01(\v2\x1c.grafana.v1.GrafanaVizConfigB\x03\xe0A\x01R\tvizConfig\"h\n" +
	"\x11GrafanaQueryGroup\x12\x17\n" +
	"\x04kind\x18\x01 \x01(\tB\x03\xe0A\x01R\x04kind\x12:\n" +
	"\x04spec\x18\x02 \x01(\v2!.grafana.v1.GrafanaQueryGroupSpecB\x03\xe0A\x01R\x04spec\"\xe4\x01\n" +
	"\x15GrafanaQueryGroupSpec\x12@\n" +
	"\aqueries\x18\x01 \x03(\v2!.grafana.v1.GrafanaPanelQueryItemB\x03\xe0A\x01R\aqueries\x12A\n" +
	"\rquery_options\x18\x02 \x01(\v2\x17.google.protobuf.StructB\x03\xe0A\x01R\fqueryOptions\x12F\n" +
	"\x0ftransformations\x18\x03 \x03(\v2\x17.google.protobuf.StructB\x03\xe0A\x01R\x0ftransformations\"l\n" +
	"\x15GrafanaPanelQueryItem\x12\x17\n" +
	"\x04kind\x18\x01 \x01(\tB\x03\xe0A\x01R\x04kind\x12:\n" +
	"\x04spec\x18\x02 \x01(\v2!.grafana.v1.GrafanaPanelQuerySpecB\x03\xe0A\x01R\x04spec\"\x89\x01\n" +
	"\x15GrafanaPanelQuerySpec\x12\x1b\n" +
	"\x06hidden\x18\x01 \x01(\bB\x03\xe0A\x01R\x06hidden\x127\n" +
	"\x05query\x18\x02 \x01(\v2\x1c.grafana.v1.GrafanaDataQueryB\x03\xe0A\x01R\x05query\x12\x1a\n" +
	"\x06ref_id\x18\x03 \x01(\tB\x03\xe0A\x01R\x05refId\"\xde\x01\n" +
	"\x10GrafanaDataQuery\x12E\n" +
	"\n" +
	"datasource\x18\x01 \x01(\v2 .grafana.v1.GrafanaDatasourceRefB\x03\xe0A\x01R\n" +
	"datasource\x12\x19\n" +
	"\x05group\x18\x02 \x01(\tB\x03\xe0A\x01R\x05group\x12\x17\n" +
	"\x04kind\x18\x03 \x01(\tB\x03\xe0A\x01R\x04kind\x120\n" +
	"\x04spec\x18\x04 \x01(\v2\x17.google.protobuf.StructB\x03\xe0A\x01R\x04spec\x12\x1d\n" +
	"\aversion\x18\x05 \x01(\tB\x03\xe0A\x01R\aversion\"_\n" +
	"\x14GrafanaDatasourceRef\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x01R\x04name\x12\x17\n" +
	"\x04type\x18\x02 \x01(\tB\x03\xe0A\x01R\x04type\x12\x15\n" +
	"\x03uid\x18\x03 \x01(\tB\x03\xe0A\x01R\x03uid\"\x97\x01\n" +
	"\x10GrafanaVizConfig\x12\x19\n" +
	"\x05group\x18\x01 \x01(\tB\x03\xe0A\x01R\x05group\x12\x17\n" +
	"\x04kind\x18\x02 \x01(\tB\x03\xe0A\x01R\x04kind\x120\n" +
	"\x04spec\x18\x03 \x01(\v2\x17.google.protobuf.StructB\x03\xe0A\x01R\x04spec\x12\x1d\n" +
	"\aversion\x18\x04 \x01(\tB\x03\xe0A\x01R\aversion\"`\n" +
	"\rGrafanaLayout\x12\x17\n" +
	"\x04kind\x18\x01 \x01(\tB\x03\xe0A\x01R\x04kind\x126\n" +
	"\x04spec\x18\x02 \x01(\v2\x1d.grafana.v1.GrafanaLayoutSpecB\x03\xe0A\x01R\x04spec\"\x8c\x01\n" +
	"\x11GrafanaLayoutSpec\x129\n" +
	"\x04rows\x18\x01 \x03(\v2 .grafana.v1.GrafanaRowsLayoutRowB\x03\xe0A\x01R\x04rows\x12<\n" +
	"\x05items\x18\x02 \x03(\v2!.grafana.v1.GrafanaGridLayoutItemB\x03\xe0A\x01R\x05items\"n\n" +
	"\x14GrafanaRowsLayoutRow\x12\x17\n" +
	"\x04kind\x18\x01 \x01(\tB\x03\xe0A\x01R\x04kind\x12=\n" +
	"\x04spec\x18\x02 \x01(\v2$.grafana.v1.GrafanaRowsLayoutRowSpecB\x03\xe0A\x01R\x04spec\"\x8e\x01\n" +
	"\x18GrafanaRowsLayoutRowSpec\x12\x1f\n" +
	"\bcollapse\x18\x01 \x01(\bB\x03\xe0A\x01R\bcollapse\x126\n" +
	"\x06layout\x18\x02 \x01(\v2\x19.grafana.v1.GrafanaLayoutB\x03\xe0A\x01R\x06layout\x12\x19\n" +
	"\x05title\x18\x03 \x01(\tB\x03\xe0A\x01R\x05title\"p\n" +
	"\x15GrafanaGridLayoutItem\x12\x17\n" +
	"\x04kind\x18\x01 \x01(\tB\x03\xe0A\x01R\x04kind\x12>\n" +
	"\x04spec\x18\x02 \x01(\v2%.grafana.v1.GrafanaGridLayoutItemSpecB\x03\xe0A\x01R\x04spec\"\xbd\x01\n" +
	"\x19GrafanaGridLayoutItemSpec\x12B\n" +
	"\aelement\x18\x01 \x01(\v2#.grafana.v1.GrafanaElementReferenceB\x03\xe0A\x01R\aelement\x12\x1b\n" +
	"\x06height\x18\x02 \x01(\x05B\x03\xe0A\x01R\x06height\x12\x19\n" +
	"\x05width\x18\x03 \x01(\x05B\x03\xe0A\x01R\x05width\x12\x11\n" +
	"\x01x\x18\x04 \x01(\x05B\x03\xe0A\x01R\x01x\x12\x11\n" +
	"\x01y\x18\x05 \x01(\x05B\x03\xe0A\x01R\x01y\"K\n" +
	"\x17GrafanaElementReference\x12\x17\n" +
	"\x04kind\x18\x01 \x01(\tB\x03\xe0A\x01R\x04kind\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tB\x03\xe0A\x01R\x04name\"\xb1\x02\n" +
	"\x13GrafanaTimeSettings\x12&\n" +
	"\fauto_refresh\x18\x01 \x01(\tB\x03\xe0A\x01R\vautoRefresh\x129\n" +
	"\x16auto_refresh_intervals\x18\x02 \x03(\tB\x03\xe0A\x01R\x14autoRefreshIntervals\x12:\n" +
	"\x17fiscal_year_start_month\x18\x03 \x01(\x05B\x03\xe0A\x01R\x14fiscalYearStartMonth\x12\x17\n" +
	"\x04from\x18\x04 \x01(\tB\x03\xe0A\x01R\x04from\x12,\n" +
	"\x0fhide_timepicker\x18\x05 \x01(\bB\x03\xe0A\x01R\x0ehideTimepicker\x12\x1f\n" +
	"\btimezone\x18\x06 \x01(\tB\x03\xe0A\x01R\btimezone\x12\x13\n" +
	"\x02to\x18\a \x01(\tB\x03\xe0A\x01R\x02to\"`\n" +
	"\x13GrafanaVariableItem\x12\x17\n" +
	"\x04kind\x18\x01 \x01(\tB\x03\xe0A\x01R\x04kind\x120\n" +
	"\x04spec\x18\x02 \x01(\v2\x17.google.protobuf.StructB\x03\xe0A\x01R\x04specB\x85\x01\n" +
	"\x0ecom.grafana.v1B\rMetadataProtoP\x01Zbgithub.com/the-protobuf-project/telemetry/telemetry-go/protobuf/grafana/v1/grafanapbv1;grafanapbv1b\x06proto3"

var (
	file_grafana_v1_metadata_proto_rawDescOnce sync.Once
	file_grafana_v1_metadata_proto_rawDescData []byte
)

func file_grafana_v1_metadata_proto_rawDescGZIP() []byte {
	file_grafana_v1_metadata_proto_rawDescOnce.Do(func() {
		file_grafana_v1_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grafana_v1_metadata_proto_rawDesc), len(file_grafana_v1_metadata_proto_rawDesc)))
	})
	return file_grafana_v1_metadata_proto_rawDescData
}

var file_grafana_v1_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_grafana_v1_metadata_proto_goTypes = []any{
	(*GrafanaDashboardAccessMeta)(nil), // 0: grafana.v1.GrafanaDashboardAccessMeta
	(*GrafanaObjectMeta)(nil),          // 1: grafana.v1.GrafanaObjectMeta
	(*GrafanaDashboardSpec)(nil),       // 2: grafana.v1.GrafanaDashboardSpec
	(*GrafanaAnnotationItem)(nil),      // 3: grafana.v1.GrafanaAnnotationItem
	(*GrafanaAnnotationSpec)(nil),      // 4: grafana.v1.GrafanaAnnotationSpec
	(*GrafanaPanelElement)(nil),        // 5: grafana.v1.GrafanaPanelElement
	(*GrafanaPanelSpec)(nil),           // 6: grafana.v1.GrafanaPanelSpec
	(*GrafanaQueryGroup)(nil),          // 7: grafana.v1.GrafanaQueryGroup
	(*GrafanaQueryGroupSpec)(nil),      // 8: grafana.v1.GrafanaQueryGroupSpec
	(*GrafanaPanelQueryItem)(nil),      // 9: grafana.v1.GrafanaPanelQueryItem
	(*GrafanaPanelQuerySpec)(nil),      // 10: grafana.v1.GrafanaPanelQuerySpec
	(*GrafanaDataQuery)(nil),           // 11: grafana.v1.GrafanaDataQuery
	(*GrafanaDatasourceRef)(nil),       // 12: grafana.v1.GrafanaDatasourceRef
	(*GrafanaVizConfig)(nil),           // 13: grafana.v1.GrafanaVizConfig
	(*GrafanaLayout)(nil),              // 14: grafana.v1.GrafanaLayout
	(*GrafanaLayoutSpec)(nil),          // 15: grafana.v1.GrafanaLayoutSpec
	(*GrafanaRowsLayoutRow)(nil),       // 16: grafana.v1.GrafanaRowsLayoutRow
	(*GrafanaRowsLayoutRowSpec)(nil),   // 17: grafana.v1.GrafanaRowsLayoutRowSpec
	(*GrafanaGridLayoutItem)(nil),      // 18: grafana.v1.GrafanaGridLayoutItem
	(*GrafanaGridLayoutItemSpec)(nil),  // 19: grafana.v1.GrafanaGridLayoutItemSpec
	(*GrafanaElementReference)(nil),    // 20: grafana.v1.GrafanaElementReference
	(*GrafanaTimeSettings)(nil),        // 21: grafana.v1.GrafanaTimeSettings
	(*GrafanaVariableItem)(nil),        // 22: grafana.v1.GrafanaVariableItem
	nil,                                // 23: grafana.v1.GrafanaObjectMeta.LabelsEntry
	nil,                                // 24: grafana.v1.GrafanaObjectMeta.AnnotationsEntry
	nil,                                // 25: grafana.v1.GrafanaDashboardSpec.ElementsEntry
	(*structpb.Struct)(nil),            // 26: google.protobuf.Struct
}
var file_grafana_v1_metadata_proto_depIdxs = []int32{
	1,  // 0: grafana.v1.GrafanaDashboardAccessMeta.metadata:type_name -> grafana.v1.GrafanaObjectMeta
	2,  // 1: grafana.v1.GrafanaDashboardAccessMeta.spec:type_name -> grafana.v1.GrafanaDashboardSpec
	26, // 2: grafana.v1.GrafanaDashboardAccessMeta.status:type_name -> google.protobuf.Struct
	23, // 3: grafana.v1.GrafanaObjectMeta.labels:type_name -> grafana.v1.GrafanaObjectMeta.LabelsEntry
	24, // 4: grafana.v1.GrafanaObjectMeta.annotations:type_name -> grafana.v1.GrafanaObjectMeta.AnnotationsEntry
	3,  // 5: grafana.v1.GrafanaDashboardSpec.annotations:type_name -> grafana.v1.GrafanaAnnotationItem
	25, // 6: grafana.v1.GrafanaDashboardSpec.elements:type_name -> grafana.v1.GrafanaDashboardSpec.ElementsEntry
	14, // 7: grafana.v1.GrafanaDashboardSpec.layout:type_name -> grafana.v1.GrafanaLayout
	26, // 8: grafana.v1.GrafanaDashboardSpec.links:type_name -> google.protobuf.Struct
	21, // 9: grafana.v1.GrafanaDashboardSpec.time_settings:type_name -> grafana.v1.GrafanaTimeSettings
	22, // 10: grafana.v1.GrafanaDashboardSpec.variables:type_name -> grafana.v1.GrafanaVariableItem
	4,  // 11: grafana.v1.GrafanaAnnotationItem.spec:type_name -> grafana.v1.GrafanaAnnotationSpec
	26, // 12: grafana.v1.GrafanaAnnotationSpec.query:type_name -> google.protobuf.Struct
	6,  // 13: grafana.v1.GrafanaPanelElement.spec:type_name -> grafana.v1.GrafanaPanelSpec
	7,  // 14: grafana.v1.GrafanaPanelSpec.data:type_name -> grafana.v1.GrafanaQueryGroup
	26, // 15: grafana.v1.GrafanaPanelSpec.links:type_name -> google.protobuf.Struct
	13, // 16: grafana.v1.GrafanaPanelSpec.viz_config:type_name -> grafana.v1.GrafanaVizConfig
	8,  // 17: grafana.v1.GrafanaQueryGroup.spec:type_name -> grafana.v1.GrafanaQueryGroupSpec
	9,  // 18: grafana.v1.GrafanaQueryGroupSpec.queries:type_name -> grafana.v1.GrafanaPanelQueryItem
	26, // 19: grafana.v1.GrafanaQueryGroupSpec.query_options:type_name -> google.protobuf.Struct
	26, // 20: grafana.v1.GrafanaQueryGroupSpec.transformations:type_name -> google.protobuf.Struct
	10, // 21: grafana.v1.GrafanaPanelQueryItem.spec:type_name -> grafana.v1.GrafanaPanelQuerySpec
	11, // 22: grafana.v1.GrafanaPanelQuerySpec.query:type_name -> grafana.v1.GrafanaDataQuery
	12, // 23: grafana.v1.GrafanaDataQuery.datasource:type_name -> grafana.v1.GrafanaDatasourceRef
	26, // 24: grafana.v1.GrafanaDataQuery.spec:type_name -> google.protobuf.Struct
	26, // 25: grafana.v1.GrafanaVizConfig.spec:type_name -> google.protobuf.Struct
	15, // 26: grafana.v1.GrafanaLayout.spec:type_name -> grafana.v1.GrafanaLayoutSpec
	16, // 27: grafana.v1.GrafanaLayoutSpec.rows:type_name -> grafana.v1.GrafanaRowsLayoutRow
	18, // 28: grafana.v1.GrafanaLayoutSpec.items:type_name -> grafana.v1.GrafanaGridLayoutItem
	17, // 29: grafana.v1.GrafanaRowsLayoutRow.spec:type_name -> grafana.v1.GrafanaRowsLayoutRowSpec
	14, // 30: grafana.v1.GrafanaRowsLayoutRowSpec.layout:type_name -> grafana.v1.GrafanaLayout
	19, // 31: grafana.v1.GrafanaGridLayoutItem.spec:type_name -> grafana.v1.GrafanaGridLayoutItemSpec
	20, // 32: grafana.v1.GrafanaGridLayoutItemSpec.element:type_name -> grafana.v1.GrafanaElementReference
	26, // 33: grafana.v1.GrafanaVariableItem.spec:type_name -> google.protobuf.Struct
	5,  // 34: grafana.v1.GrafanaDashboardSpec.ElementsEntry.value:type_name -> grafana.v1.GrafanaPanelElement
	35, // [35:35] is the sub-list for method output_type
	35, // [35:35] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_grafana_v1_metadata_proto_init() }
func file_grafana_v1_metadata_proto_init() {
	if File_grafana_v1_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grafana_v1_metadata_proto_rawDesc), len(file_grafana_v1_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grafana_v1_metadata_proto_goTypes,
		DependencyIndexes: file_grafana_v1_metadata_proto_depIdxs,
		MessageInfos:      file_grafana_v1_metadata_proto_msgTypes,
	}.Build()
	File_grafana_v1_metadata_proto = out.File
	file_grafana_v1_metadata_proto_goTypes = nil
	file_grafana_v1_metadata_proto_depIdxs = nil
}
