// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: telemetry/v1/annotations.proto

package telemetrypbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_telemetry_v1_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*TelemetryOptions)(nil),
		Field:         50100,
		Name:          "telemetry.v1.telemetry",
		Tag:           "bytes,50100,opt,name=telemetry",
		Filename:      "telemetry/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*TelemetryFieldOptions)(nil),
		Field:         50101,
		Name:          "telemetry.v1.telemetry_field",
		Tag:           "bytes,50101,opt,name=telemetry_field",
		Filename:      "telemetry/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*MetricFieldOptions)(nil),
		Field:         50102,
		Name:          "telemetry.v1.metric_field",
		Tag:           "bytes,50102,opt,name=metric_field",
		Filename:      "telemetry/v1/annotations.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// telemetry tunes the tracing (and generic op-metric on/off) a consumer
	// folds into a resource's generated instrumentation: spans, op metrics, and
	// trace-correlated logs.
	//
	// optional telemetry.v1.TelemetryOptions telemetry = 50100;
	E_Telemetry = &file_telemetry_v1_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// telemetry_field projects the field into the emitted tracing as a span
	// attribute.
	//
	// optional telemetry.v1.TelemetryFieldOptions telemetry_field = 50101;
	E_TelemetryField = &file_telemetry_v1_annotations_proto_extTypes[1]
	// metric_field overrides telemetry.v1's label inference for the generated
	// lifecycle metrics (op counter + duration histogram) — see
	// metrics.proto's MetricFieldOptions.
	//
	// optional telemetry.v1.MetricFieldOptions metric_field = 50102;
	E_MetricField = &file_telemetry_v1_annotations_proto_extTypes[2]
)

var File_telemetry_v1_annotations_proto protoreflect.FileDescriptor

const file_telemetry_v1_annotations_proto_rawDesc = "" +
	"\n" +
	"\x1etelemetry/v1/annotations.proto\x12\ftelemetry.v1\x1a google/protobuf/descriptor.proto\x1a\x1atelemetry/v1/metrics.proto\x1a\x1atelemetry/v1/tracing.proto:_\n" +
	"\ttelemetry\x12\x1f.google.protobuf.MessageOptions\x18\xb4\x87\x03 \x01(\v2\x1e.telemetry.v1.TelemetryOptionsR\ttelemetry:m\n" +
	"\x0ftelemetry_field\x12\x1d.google.protobuf.FieldOptions\x18\xb5\x87\x03 \x01(\v2#.telemetry.v1.TelemetryFieldOptionsR\x0etelemetryField:d\n" +
	"\fmetric_field\x12\x1d.google.protobuf.FieldOptions\x18\xb6\x87\x03 \x01(\v2 .telemetry.v1.MetricFieldOptionsR\vmetricFieldB\x90\x01\n" +
	"\x10com.telemetry.v1B\x10AnnotationsProtoP\x01Zhgithub.com/the-protobuf-project/telemetry/telemetry-go/protobuf/telemetry/v1/telemetrypbv1;telemetrypbv1b\x06proto3"

var file_telemetry_v1_annotations_proto_goTypes = []any{
	(*descriptorpb.MessageOptions)(nil), // 0: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 1: google.protobuf.FieldOptions
	(*TelemetryOptions)(nil),            // 2: telemetry.v1.TelemetryOptions
	(*TelemetryFieldOptions)(nil),       // 3: telemetry.v1.TelemetryFieldOptions
	(*MetricFieldOptions)(nil),          // 4: telemetry.v1.MetricFieldOptions
}
var file_telemetry_v1_annotations_proto_depIdxs = []int32{
	0, // 0: telemetry.v1.telemetry:extendee -> google.protobuf.MessageOptions
	1, // 1: telemetry.v1.telemetry_field:extendee -> google.protobuf.FieldOptions
	1, // 2: telemetry.v1.metric_field:extendee -> google.protobuf.FieldOptions
	2, // 3: telemetry.v1.telemetry:type_name -> telemetry.v1.TelemetryOptions
	3, // 4: telemetry.v1.telemetry_field:type_name -> telemetry.v1.TelemetryFieldOptions
	4, // 5: telemetry.v1.metric_field:type_name -> telemetry.v1.MetricFieldOptions
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	3, // [3:6] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_telemetry_v1_annotations_proto_init() }
func file_telemetry_v1_annotations_proto_init() {
	if File_telemetry_v1_annotations_proto != nil {
		return
	}
	file_telemetry_v1_metrics_proto_init()
	file_telemetry_v1_tracing_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_v1_annotations_proto_rawDesc), len(file_telemetry_v1_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_telemetry_v1_annotations_proto_goTypes,
		DependencyIndexes: file_telemetry_v1_annotations_proto_depIdxs,
		ExtensionInfos:    file_telemetry_v1_annotations_proto_extTypes,
	}.Build()
	File_telemetry_v1_annotations_proto = out.File
	file_telemetry_v1_annotations_proto_goTypes = nil
	file_telemetry_v1_annotations_proto_depIdxs = nil
}
