// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: telemetry/v1/metrics.proto

package telemetrypbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MetricKind selects the instrument a value field (MetricFieldOptions.value)
// is recorded through.
type MetricKind int32

const (
	// Auto-detect: a field name that looks duration/size-like ("latency",
	// "duration_ms", "size_bytes", "elapsed", ...) resolves to
	// METRIC_KIND_HISTOGRAM; everything else resolves to METRIC_KIND_GAUGE.
	// METRIC_KIND_COUNTER and METRIC_KIND_UP_DOWN_COUNTER are never
	// auto-detected — a single scalar field can't safely be assumed monotonic —
	// so pick one explicitly via MetricFieldOptions.kind when that's what you
	// want.
	MetricKind_METRIC_KIND_UNSPECIFIED MetricKind = 0
	// Counter is a monotonic increasing instrument, e.g. "total number of
	// requests". It is the only instrument that can be used with a
	// METRIC_KIND_HISTOGRAM, which is a special case of a counter that
	// records the distribution of values over time.
	MetricKind_METRIC_KIND_COUNTER MetricKind = 1
	// UpDownCounter is a non-monotonic instrument, e.g. "current number of
	// active users". It can go up and down, but is still a single scalar value
	// at any given time.
	MetricKind_METRIC_KIND_UP_DOWN_COUNTER MetricKind = 2
	// Gauge records a single scalar value at the time it's set, e.g. "current
	// queue depth". This is the default auto-detected kind.
	MetricKind_METRIC_KIND_GAUGE MetricKind = 3
	// Histogram records the statistical distribution of values over time,
	// e.g. request latency buckets.
	MetricKind_METRIC_KIND_HISTOGRAM MetricKind = 4
)

// Enum value maps for MetricKind.
var (
	MetricKind_name = map[int32]string{
		0: "METRIC_KIND_UNSPECIFIED",
		1: "METRIC_KIND_COUNTER",
		2: "METRIC_KIND_UP_DOWN_COUNTER",
		3: "METRIC_KIND_GAUGE",
		4: "METRIC_KIND_HISTOGRAM",
	}
	MetricKind_value = map[string]int32{
		"METRIC_KIND_UNSPECIFIED":     0,
		"METRIC_KIND_COUNTER":         1,
		"METRIC_KIND_UP_DOWN_COUNTER": 2,
		"METRIC_KIND_GAUGE":           3,
		"METRIC_KIND_HISTOGRAM":       4,
	}
)

func (x MetricKind) Enum() *MetricKind {
	p := new(MetricKind)
	*p = x
	return p
}

func (x MetricKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricKind) Descriptor() protoreflect.EnumDescriptor {
	return file_telemetry_v1_metrics_proto_enumTypes[0].Descriptor()
}

func (MetricKind) Type() protoreflect.EnumType {
	return &file_telemetry_v1_metrics_proto_enumTypes[0]
}

func (x MetricKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricKind.Descriptor instead.
func (MetricKind) EnumDescriptor() ([]byte, []int) {
	return file_telemetry_v1_metrics_proto_rawDescGZIP(), []int{0}
}

// metrics.proto holds the metrics half of telemetry.v1: MetricFieldOptions
// below tunes which fields become metric labels on the inferred lifecycle
// metrics (op counter + duration histogram) protoc-gen-telemetry generates,
// and separately lets a numeric field be recorded as its own metric (a value,
// not a label) with an auto-detected or explicit instrument kind. The richer
// custom-metric annotations (an application raising its own named metric not
// tied to any one field, e.g. "book_checked_out_total") are a separate,
// larger addition reserved for later.
//
// Applied via:
//
//	string region = 6 [(telemetry.v1.metric_field) = { label: true }];   // force a normally-excluded field in
//	bool is_active = 7 [(telemetry.v1.metric_field) = { label: false }]; // opt an auto-labeled field out
//	int32 page_count = 8 [(telemetry.v1.metric_field) = { value: true }]; // record as its own metric, kind auto-detected (GAUGE here)
//	double duration_ms = 9 [(telemetry.v1.metric_field) = { value: true, kind: METRIC_KIND_HISTOGRAM, unit: "ms" }]; // explicit kind + unit
type MetricFieldOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// label overrides telemetry.v1's inference for this field (bool and enum
	// fields are labeled by default; everything else is not, since metric
	// labels must stay low-cardinality — see tracing.proto's TelemetryFieldOptions
	// doc for why spans don't have this restriction). Explicit presence is what
	// makes this an override rather than a default: unset inherits inference,
	// true forces a field in (protoc-gen-telemetry warns at generate time if the
	// field's type makes it a poor label candidate), false opts an
	// auto-inferred field out.
	Label *bool `protobuf:"varint,1,opt,name=label,proto3,oneof" json:"label,omitempty"`
	// label_key overrides the metric label key for this field. Defaults to
	// the field's snake_case name.
	LabelKey string `protobuf:"bytes,2,opt,name=label_key,json=labelKey,proto3" json:"label_key,omitempty"`
	// value opts this field in as its own recorded metric (a Counter,
	// UpDownCounter, Gauge, or Histogram instrument — see kind), in addition to
	// (or instead of) being a label. Only meaningful on a numeric field
	// (int32/64, uint32/64, float, double); protoc-gen-telemetry warns and
	// ignores it on any other field type, since there's no such thing as a
	// string- or message-valued instrument. Unlike label, value has no
	// inference of its own to override — a field only becomes a value metric
	// when this is explicitly true, since not every numeric field (e.g. a
	// "version" counter-of-a-different-kind) is metric-worthy.
	Value bool `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	// kind selects the instrument a value field (value=true) is recorded
	// through. METRIC_KIND_UNSPECIFIED (the default) auto-detects; see
	// MetricKind's doc for the exact rule.
	Kind MetricKind `protobuf:"varint,4,opt,name=kind,proto3,enum=telemetry.v1.MetricKind" json:"kind,omitempty"`
	// metric overrides the generated metric's name for a value field. Defaults
	// to "<resource_snake>_<field_snake>".
	Metric string `protobuf:"bytes,5,opt,name=metric,proto3" json:"metric,omitempty"`
	// unit overrides a value field's instrument unit (UCUM-style, e.g. "1",
	// "ms", "By"). Defaults to "1", except an auto-detected METRIC_KIND_HISTOGRAM
	// defaults to "ms".
	Unit string `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	// buckets overrides a value field's histogram bucket boundaries. Only
	// meaningful when kind resolves to METRIC_KIND_HISTOGRAM (explicitly or by
	// auto-detection); ignored otherwise.
	Buckets       []float64 `protobuf:"fixed64,7,rep,packed,name=buckets,proto3" json:"buckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricFieldOptions) Reset() {
	*x = MetricFieldOptions{}
	mi := &file_telemetry_v1_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricFieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricFieldOptions) ProtoMessage() {}

func (x *MetricFieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricFieldOptions.ProtoReflect.Descriptor instead.
func (*MetricFieldOptions) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *MetricFieldOptions) GetLabel() bool {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return false
}

func (x *MetricFieldOptions) GetLabelKey() string {
	if x != nil {
		return x.LabelKey
	}
	return ""
}

func (x *MetricFieldOptions) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

func (x *MetricFieldOptions) GetKind() MetricKind {
	if x != nil {
		return x.Kind
	}
	return MetricKind_METRIC_KIND_UNSPECIFIED
}

func (x *MetricFieldOptions) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *MetricFieldOptions) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *MetricFieldOptions) GetBuckets() []float64 {
	if x != nil {
		return x.Buckets
	}
	return nil
}

var File_telemetry_v1_metrics_proto protoreflect.FileDescriptor

const file_telemetry_v1_metrics_proto_rawDesc = "" +
	"\n" +
	"\x1atelemetry/v1/metrics.proto\x12\ftelemetry.v1\"\xe0\x01\n" +
	"\x12MetricFieldOptions\x12\x19\n" +
	"\x05label\x18\x01 \x01(\bH\x00R\x05label\x88\x01\x01\x12\x1b\n" +
	"\tlabel_key\x18\x02 \x01(\tR\blabelKey\x12\x14\n" +
	"\x05value\x18\x03 \x01(\bR\x05value\x12,\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x18.telemetry.v1.MetricKindR\x04kind\x12\x16\n" +
	"\x06metric\x18\x05 \x01(\tR\x06metric\x12\x12\n" +
	"\x04unit\x18\x06 \x01(\tR\x04unit\x12\x18\n" +
	"\abuckets\x18\a \x03(\x01R\abucketsB\b\n" +
	"\x06_label*\x95\x01\n" +
	"\n" +
	"MetricKind\x12\x1b\n" +
	"\x17METRIC_KIND_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13METRIC_KIND_COUNTER\x10\x01\x12\x1f\n" +
	"\x1bMETRIC_KIND_UP_DOWN_COUNTER\x10\x02\x12\x15\n" +
	"\x11METRIC_KIND_GAUGE\x10\x03\x12\x19\n" +
	"\x15METRIC_KIND_HISTOGRAM\x10\x04B\x8c\x01\n" +
	"\x10com.telemetry.v1B\fMetricsProtoP\x01Zhgithub.com/the-protobuf-project/telemetry/telemetry-go/protobuf/telemetry/v1/telemetrypbv1;telemetrypbv1b\x06proto3"

var (
	file_telemetry_v1_metrics_proto_rawDescOnce sync.Once
	file_telemetry_v1_metrics_proto_rawDescData []byte
)

func file_telemetry_v1_metrics_proto_rawDescGZIP() []byte {
	file_telemetry_v1_metrics_proto_rawDescOnce.Do(func() {
		file_telemetry_v1_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_v1_metrics_proto_rawDesc), len(file_telemetry_v1_metrics_proto_rawDesc)))
	})
	return file_telemetry_v1_metrics_proto_rawDescData
}

var file_telemetry_v1_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_telemetry_v1_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_telemetry_v1_metrics_proto_goTypes = []any{
	(MetricKind)(0),            // 0: telemetry.v1.MetricKind
	(*MetricFieldOptions)(nil), // 1: telemetry.v1.MetricFieldOptions
}
var file_telemetry_v1_metrics_proto_depIdxs = []int32{
	0, // 0: telemetry.v1.MetricFieldOptions.kind:type_name -> telemetry.v1.MetricKind
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_telemetry_v1_metrics_proto_init() }
func file_telemetry_v1_metrics_proto_init() {
	if File_telemetry_v1_metrics_proto != nil {
		return
	}
	file_telemetry_v1_metrics_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_v1_metrics_proto_rawDesc), len(file_telemetry_v1_metrics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_telemetry_v1_metrics_proto_goTypes,
		DependencyIndexes: file_telemetry_v1_metrics_proto_depIdxs,
		EnumInfos:         file_telemetry_v1_metrics_proto_enumTypes,
		MessageInfos:      file_telemetry_v1_metrics_proto_msgTypes,
	}.Build()
	File_telemetry_v1_metrics_proto = out.File
	file_telemetry_v1_metrics_proto_goTypes = nil
	file_telemetry_v1_metrics_proto_depIdxs = nil
}
