// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: telemetry/v1/tracing.proto

package telemetrypbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TelemetryOptions tunes the per-resource tracing (and generic op-metrics
// on/off) a consumer folds into its generated instrumentation: a span per
// operation, an ops counter + duration histogram, and trace-correlated error
// logs. This module is deliberately not ORM-specific — any codegen target can
// read these annotations — but today the gorm target is its only consumer,
// applying it only when its own `telemetry` plugin opt (or orm.yaml
// `telemetry.enabled`) is on; without that, these annotations are inert.
//
// Applied via:
//
//	option (telemetry.v1.telemetry) = { span_prefix: "bookstore.Book" };
//	option (telemetry.v1.telemetry) = { enabled: false };  // opt this table out
type TelemetryOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// enabled overrides the tree-wide default (every resource is instrumented
	// when the consumer's telemetry opt is on). Explicit presence matters:
	// `enabled: false` strips this resource's instrumentation; unset inherits
	// the default.
	Enabled *bool `protobuf:"varint,1,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	// span_prefix overrides the generated span-name prefix. Defaults to
	// "<schema>.<Model>", e.g. "bookstore_v1.Book" → span
	// "bookstore_v1.Book/Create".
	SpanPrefix string `protobuf:"bytes,2,opt,name=span_prefix,json=spanPrefix,proto3" json:"span_prefix,omitempty"`
	// metrics overrides per-resource metric recording (the ops counter +
	// duration histogram). Defaults to the consumer's telemetry.metrics setting
	// (true). Spans are unaffected. This is the same generic DB-scoped op-metric
	// toggle as today — Phase B's custom domain-metric specs (metrics.proto)
	// build on top of this gate rather than replacing it.
	Metrics       *bool `protobuf:"varint,3,opt,name=metrics,proto3,oneof" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryOptions) Reset() {
	*x = TelemetryOptions{}
	mi := &file_telemetry_v1_tracing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryOptions) ProtoMessage() {}

func (x *TelemetryOptions) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_tracing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryOptions.ProtoReflect.Descriptor instead.
func (*TelemetryOptions) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_tracing_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryOptions) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *TelemetryOptions) GetSpanPrefix() string {
	if x != nil {
		return x.SpanPrefix
	}
	return ""
}

func (x *TelemetryOptions) GetMetrics() bool {
	if x != nil && x.Metrics != nil {
		return *x.Metrics
	}
	return false
}

// TelemetryFieldOptions projects a field into the tracing emitted around its
// resource's operations, as a span attribute. Metrics stay DB-scoped by
// design — only table, op, and status label the generated op metrics;
// domain-level metrics are a separate concern (see metrics.proto).
//
// Applied via:
//
//	string author_id = 4 [(telemetry.v1.telemetry_field) = { label: true }];
//	string state = 5 [(telemetry.v1.telemetry_field) = { label: true, label_key: "book.state" }];
type TelemetryFieldOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// label includes this field as a span attribute on traced write operations.
	// Safe for any cardinality — spans absorb per-row values.
	Label bool `protobuf:"varint,1,opt,name=label,proto3" json:"label,omitempty"`
	// label_key overrides the attribute name for this field. Defaults to
	// "<model_snake>.<column>", e.g. "book.genre".
	LabelKey      string `protobuf:"bytes,2,opt,name=label_key,json=labelKey,proto3" json:"label_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryFieldOptions) Reset() {
	*x = TelemetryFieldOptions{}
	mi := &file_telemetry_v1_tracing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryFieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryFieldOptions) ProtoMessage() {}

func (x *TelemetryFieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_tracing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryFieldOptions.ProtoReflect.Descriptor instead.
func (*TelemetryFieldOptions) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_tracing_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryFieldOptions) GetLabel() bool {
	if x != nil {
		return x.Label
	}
	return false
}

func (x *TelemetryFieldOptions) GetLabelKey() string {
	if x != nil {
		return x.LabelKey
	}
	return ""
}

var File_telemetry_v1_tracing_proto protoreflect.FileDescriptor

const file_telemetry_v1_tracing_proto_rawDesc = "" +
	"\n" +
	"\x1atelemetry/v1/tracing.proto\x12\ftelemetry.v1\"\x89\x01\n" +
	"\x10TelemetryOptions\x12\x1d\n" +
	"\aenabled\x18\x01 \x01(\bH\x00R\aenabled\x88\x01\x01\x12\x1f\n" +
	"\vspan_prefix\x18\x02 \x01(\tR\n" +
	"spanPrefix\x12\x1d\n" +
	"\ametrics\x18\x03 \x01(\bH\x01R\ametrics\x88\x01\x01B\n" +
	"\n" +
	"\b_enabledB\n" +
	"\n" +
	"\b_metrics\"J\n" +
	"\x15TelemetryFieldOptions\x12\x14\n" +
	"\x05label\x18\x01 \x01(\bR\x05label\x12\x1b\n" +
	"\tlabel_key\x18\x02 \x01(\tR\blabelKeyB\x8c\x01\n" +
	"\x10com.telemetry.v1B\fTracingProtoP\x01Zhgithub.com/the-protobuf-project/telemetry/telemetry-go/protobuf/telemetry/v1/telemetrypbv1;telemetrypbv1b\x06proto3"

var (
	file_telemetry_v1_tracing_proto_rawDescOnce sync.Once
	file_telemetry_v1_tracing_proto_rawDescData []byte
)

func file_telemetry_v1_tracing_proto_rawDescGZIP() []byte {
	file_telemetry_v1_tracing_proto_rawDescOnce.Do(func() {
		file_telemetry_v1_tracing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_v1_tracing_proto_rawDesc), len(file_telemetry_v1_tracing_proto_rawDesc)))
	})
	return file_telemetry_v1_tracing_proto_rawDescData
}

var file_telemetry_v1_tracing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_telemetry_v1_tracing_proto_goTypes = []any{
	(*TelemetryOptions)(nil),      // 0: telemetry.v1.TelemetryOptions
	(*TelemetryFieldOptions)(nil), // 1: telemetry.v1.TelemetryFieldOptions
}
var file_telemetry_v1_tracing_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_telemetry_v1_tracing_proto_init() }
func file_telemetry_v1_tracing_proto_init() {
	if File_telemetry_v1_tracing_proto != nil {
		return
	}
	file_telemetry_v1_tracing_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_v1_tracing_proto_rawDesc), len(file_telemetry_v1_tracing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_telemetry_v1_tracing_proto_goTypes,
		DependencyIndexes: file_telemetry_v1_tracing_proto_depIdxs,
		MessageInfos:      file_telemetry_v1_tracing_proto_msgTypes,
	}.Build()
	File_telemetry_v1_tracing_proto = out.File
	file_telemetry_v1_tracing_proto_goTypes = nil
	file_telemetry_v1_tracing_proto_depIdxs = nil
}
