apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: telemetry

resources:
  - namespace.yaml
  - secrets.yaml
  - configmaps.yaml
  - deployments.yaml
  - services.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: telemetry-telemetry
  app.kubernetes.io/managed-by: kustomize
